(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.webFontTxtInst = {}; 
var loadedTypekitCount = 0;
var loadedGoogleCount = 0;
var gFontsUpdateCacheList = [];
var tFontsUpdateCacheList = [];
lib.ssMetadata = [
		{name:"index_atlas_NP_", frames: [[312,252,135,52],[0,0,970,250],[312,306,62,56],[0,252,310,190]]}
];



lib.updateListCache = function (cacheList) {		
	for(var i = 0; i < cacheList.length; i++) {		
		if(cacheList[i].cacheCanvas)		
			cacheList[i].updateCache();		
	}		
};		

lib.addElementsToCache = function (textInst, cacheList) {		
	var cur = textInst;		
	while(cur != null && cur != exportRoot) {		
		if(cacheList.indexOf(cur) != -1)		
			break;		
		cur = cur.parent;		
	}		
	if(cur != exportRoot) {		
		var cur2 = textInst;		
		var index = cacheList.indexOf(cur);		
		while(cur2 != null && cur2 != cur) {		
			cacheList.splice(index, 0, cur2);		
			cur2 = cur2.parent;		
			index++;		
		}		
	}		
	else {		
		cur = textInst;		
		while(cur != null && cur != exportRoot) {		
			cacheList.push(cur);		
			cur = cur.parent;		
		}		
	}		
};		

lib.gfontAvailable = function(family, totalGoogleCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], gFontsUpdateCacheList);		

	loadedGoogleCount++;		
	if(loadedGoogleCount == totalGoogleCount) {		
		lib.updateListCache(gFontsUpdateCacheList);		
	}		
};		

lib.tfontAvailable = function(family, totalTypekitCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], tFontsUpdateCacheList);		

	loadedTypekitCount++;		
	if(loadedTypekitCount == totalTypekitCount) {		
		lib.updateListCache(tFontsUpdateCacheList);		
	}		
};
// symbols:



(lib.fourteenbottomleft = function() {
	this.spriteSheet = ss["index_atlas_NP_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.fourteenbottomright = function() {
	this.initialize(img.fourteenbottomright);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,295,187);


(lib.fourteentable = function() {
	this.spriteSheet = ss["index_atlas_NP_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.fourteentopleft = function() {
	this.spriteSheet = ss["index_atlas_NP_"];
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();



(lib.fourteentopright = function() {
	this.spriteSheet = ss["index_atlas_NP_"];
	this.gotoAndStop(3);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.topleftfourteen = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.fourteentopleft();
	this.instance.parent = this;
	this.instance.setTransform(-31,-28);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.topleftfourteen, new cjs.Rectangle(-31,-28,62,56), null);


(lib.sweetinspiration = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E47").s().p("AiTCVQgPgFAAgNQAAgKAPgGIAHgDQAIgEADgLQAEgKAAgWIgBgVIAAgYIAAgeQAAgvgCgPQgDgOgGgDIgOgFQgSgGAAgKQAAgHAGgFQAFgFANgGIAsgNIAfgGQAIAAAEAFQADAEAAAKIAAAUIABADIACABIACAAIABgBIAHgGIAGgGQAggfAlAAQAWAAAUAKQAUAJAOAQQAOARAGAWQAFAXAAAwIAAAoIAAAUIAAARQAAAVADAJQADAJAHAEIAIADQAPAGAAAKQAAANgOAEQgOAFguAAQgqAAgOgEQgPgFAAgLQAAgMAPgFIAMgFQAHgEACgNQADgNAAghQAAhegMgZQgMgYggAAQgPAAgOAKQgPAJgIARQgGANgDAXQgDAXAAA7QAAAdADAKQACAJAHAEIALAFQAPAFAAAMQAAALgPAFQgOAFgoAAQgtAAgPgFg");
	this.shape.setTransform(131.9,42.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E47").s().p("AhtBxQgqgtAAhDQAAhDAtgsQAsgtBDAAQBAgBAqArQApAqAABCQAABEgsAuQgtAwhAAAQhBAAgrgsgAg5hZQgSAYAAAoQAAA7AZApQAZAoAkAAQAdAAATgaQASgZAAgoQAAg5gagpQgZgngjAAQgeAAgSAYg");
	this.shape_1.setTransform(96.8,42.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E47").s().p("Ag1DWQgOgFAAgNQAAgKAOgFIAHgEQAJgEACgKQAEgKAAgXIAAgUIAAgYIAAgfQAAgwgDgNQgCgOgHgEIgNgFQgSgGAAgKQAAgGAFgFQAFgGAOgFIAtgOIAfgGQAIAAADAGQAEAFAAAOIAAASIAAANIgDBMIAAACIgBBKQAAAcADAMQACAMAHADIALAFQAQAGAAALQAAAMgQAFQgOAEgoAAQgsAAgPgFgAgliXQgMgKAAgQQAAgRAOgMQAOgMAUAAQATAAANALQANALgBAQQABARgOALQgOAMgUAAQgUAAgNgLg");
	this.shape_2.setTransform(70.9,35.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E47").s().p("AgQC0QgPgFgKgJQgLgKgEgRQgFgQAAgtIAAigIgbAAIgJgDIgCgHIAAgIQAAgJAfgbIAMgLIAMgKQAfgbALAAIAJACQADADAAAEIAAA5IBEAAQAHAAADACQADADAAAJIAAAHQAAAIgDADQgEAEgGAAIg+AAIgFACIgCAHIAACUQAAAnAHAKQAGAKASAAQAJAAAPgFIAVgFQAGAAAFAEQAEAEAAAGQAAAQgZAQQgaAPggAAQgSAAgPgFg");
	this.shape_3.setTransform(51.7,39.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E47").s().p("AA1CNIgQgQIgNAHQglAZgkAAQgsAAgbgaQgbgZAAgqQAAgwAigZQAjgbA/AAQAPAAAHAEQAIAEAAAMQAAARgVAAQgdAAgSAOQgSAPAAAZQAAAYAPAOQAQAPAbAAQAcAAANgNQAMgNAAggIAAhxQAAgagMgPQgLgOgUAAQgPAAgNAHQgMAGgMANIgHAIQgSAXgUAAQgMAAgHgHQgHgIAAgNQAAgcAjgTQAjgUA2AAQAhAAAYAJQAYAJANARQAJALAEASQADATAAArIAABgQAAARADAIQADAIAGACIAJADQATAFAAAKQAAAOgUAMQgUAMgbAAQgNAAgPgQg");
	this.shape_4.setTransform(24.8,42.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E47").s().p("AhaCVQgPgFAAgNQAAgKAOgGIAJgDQAHgEAEgLQACgKAAgWIAAgVIAAgYIAAgRQAAg3gCgRQgDgQgGgEIgOgFQgSgGAAgKQAAgHAFgFQAFgFAOgGIApgNIAbgFQANAAAGApIABAGIABABQAPgYASgNQAQgNARAAQAVAAAMANQANAMAAAVQAAAVgKAMQgJAMgRAAIgPgDIgNgJIgHgLQgDgIgDAAQgVAAgIAdQgHAcAABbQgBAaADANQAEANAHAEIANAEQARAGABAMQAAALgRAFQgRAFgpAAQgtAAgOgFg");
	this.shape_5.setTransform(-2.7,42.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E47").s().p("Ag1DWQgPgFAAgNQAAgKAPgFIAIgEQAHgEAEgKQADgKAAgXIgBgUIAAgYIAAgfQABgwgDgNQgDgOgGgEIgOgFQgSgGAAgKQAAgGAGgFQAFgGANgFIAugOIAfgGQAIAAADAGQAEAFAAAOIAAASIgBANIgCBMIAAACIgBBKQAAAcACAMQADAMAHADIALAFQAPAGAAALQABAMgPAFQgPAEgnAAQgtAAgPgFgAgkiXQgNgKgBgQQAAgRAPgMQAOgMAUAAQATAAAMALQAOALAAAQQAAARgPALQgNAMgVAAQgTAAgMgLg");
	this.shape_6.setTransform(-24,35.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006E47").s().p("AiRDNQgPgFAAgNQgBgKANgFIAQgIQAGgGACgYQACgXAAhLIAAgwQABhSgDgXQgDgYgHgEIgOgFQgSgGAAgKQAAgHAGgGQAFgEANgFIAqgNQATgGALAAQAIAAAEAFQAEAEAAALIAAAPIABAGIABACIALgJIAMgIQASgOARgHQARgGARAAQA4gBAjApQAkApAABBQAABIgoAuQgnAug+AAQgaAAgJgHQgKgIAAgLQAAgHAFgFQAEgFAKABIAHABIALABQAgAAAVgcQATgcABgtQAAg0gWgfQgWgfgigBQgfAAgRASQgTASABAtIAAC+IABAeQACALAEAFQADAEANAEIANAEIAGAFIACAJQAAALgRAFQgSAFgrgBQgrAAgPgEg");
	this.shape_7.setTransform(-51.4,47.9);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006E47").s().p("AgWCcIgggGIgJAGIgKACIgGgCIgGgEQgKgIgIgYQgJgZAAgWQAAgJAFgHQAFgGAIAAQAOAAAOAYIALASQAJAMAQAHQAPAHARAAQAUAAAMgKQALgKAAgRQAAgZgxgYIgSgJQgugXgRgTQgQgTAAgdQAAgnAbgYQAbgZAsAAIAUABIAVAEIAOgGIAKgCQAOAAAOAYQAOAYAAAaQAAAKgEAGQgFAGgJAAQgHAAgGgFQgHgGgJgPQgLgSgMgHQgMgIgRAAQgQAAgLAKQgLAKAAAPQAAAOALALQALAKAlATIADACQBUAoAAAxQAAApggAdQghAcgwAAg");
	this.shape_8.setTransform(-81.8,42.4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006E47").s().p("AiTCVQgPgFAAgNQAAgKAPgGIAHgDQAIgEADgLQAEgKAAgWIgBgVIAAgYIAAgeQAAgvgCgPQgDgOgGgDIgOgFQgSgGAAgKQAAgHAGgFQAFgFANgGIAsgNIAfgGQAIAAAEAFQADAEAAAKIAAAUIABADIACABIACAAIABgBIAHgGIAGgGQAggfAlAAQAWAAAUAKQAUAJAOAQQAOARAGAWQAFAXAAAwIAAAoIAAAUIAAARQAAAVADAJQADAJAHAEIAIADQAPAGAAAKQAAANgOAEQgOAFguAAQgqAAgOgEQgPgFAAgLQAAgMAPgFIAMgFQAHgEACgNQADgNAAghQAAhegMgZQgMgYggAAQgPAAgOAKQgPAJgIARQgGANgDAXQgDAXAAA7QAAAdADAKQACAJAHAEIALAFQAPAFAAAMQAAALgPAFQgOAFgoAAQgtAAgPgFg");
	this.shape_9.setTransform(-113,42.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006E47").s().p("Ag+DTQgSgFABgNQAAgMASgHIANgHQAGgFADgkQADgkAAheIgChwQgDgsgEgFQgDgFgQgGQgPgHAAgMQAAgLANgFQANgFA1AAQA2ABANAEQAOAEAAAMQgBAMgSAIIgOAGQgFAEgDAeIgCBjIACCOQACA1AEAFQADAFAQAGQAQAGAAAMQgBANgQAFQgRAGgvAAQguAAgQgGg");
	this.shape_10.setTransform(-140.7,36);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006E47").s().p("AgQC0QgPgFgKgJQgLgKgEgRQgFgQAAgtIAAigIgbAAIgJgDIgCgHIAAgIQAAgJAfgbIAMgLIAMgKQAfgbALAAIAJACQADADAAAEIAAA5IBEAAQAHAAADACQADADAAAJIAAAHQAAAIgDADQgEAEgGAAIg+AAIgFACIgCAHIAACUQAAAnAHAKQAGAKASAAQAJAAAPgFIAVgFQAGAAAFAEQAEAEAAAGQAAAQgZAQQgaAPggAAQgSAAgPgFg");
	this.shape_11.setTransform(9.5,-31.6);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#006E47").s().p("AhhBxQgrgsAAhBQAAhFAsgtQAsguBDAAQA7AAAhAiQAiAgAAA5QAAASgFAGQgGAGgXAAIhyAAQgKAAgFgFQgGgFAAgIQAAgIAGgEQAFgFAKAAIA+AAIAPgCQAEgCAAgHQAAgdgTgTQgUgUgbAAQgkAAgRAfQgRAggBArQAAAuAYAiQAYAjAlgBQAXAAAPgEQAQgFAOgKIALgJQAPgMAIAAQAGAAAFAEQAEAEAAAGQAAAIgHAKQgIALgMAKQgbAWgYAJQgYAJgdAAQg+AAgrgrg");
	this.shape_12.setTransform(-17.5,-28.7);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#006E47").s().p("AhhBxQgrgsAAhBQAAhFAsgtQAsguBDAAQA6AAAiAiQAiAgAAA5QAAASgGAGQgFAGgXAAIhyAAQgKAAgFgFQgFgFgBgIQABgIAFgEQAFgFAKAAIA+AAIAPgCQAEgCAAgHQAAgdgUgTQgTgUgbAAQgkAAgRAfQgSAgAAArQAAAuAYAiQAZAjAlgBQAWAAAPgEQAQgFAOgKIALgJQAPgMAIAAQAHAAAEAEQAEAEABAGQgBAIgHAKQgHALgNAKQgaAWgZAJQgYAJgdAAQg+AAgrgrg");
	this.shape_13.setTransform(-49.6,-28.7);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#006E47").s().p("AARAhIgkheQgRgqgOgHIgIgEQgSgHAAgLQAAgMAPgFQAPgFAwAAQApAAAPAFQAOAFAAAMIgCAJIgGAGIgKAEQgMAFAAAHIAFAUIAZA+IAaA6QAHANADAAQAFAAAFgIIAOgaIAghLQALgeAAgKIgDgKIgHgHIgIgEQgOgFAAgKQAAgLAOgFQANgFAlAAQAgAAANAFQAMAFAAALQAAAMgPAFIgLAEQgOAHgbA+IgGAPIgNAcQhECbgUAAQgUAAg1h6gAiwARIgIgTIgUgzQgUgzgNgGIgJgEQgRgHAAgLQAAgMAPgFQAPgFAxAAQApAAAOAFQAOAFAAAMIgBAJIgGAGIgKAEQgMAFAAAHIAHAZIAWA5IAZA4QAIAPAEAAQAJAAAIgSIAKgWIAHgJQAEgDAHAAQAHAAAEAEQAEAFAAAHQAAAIgIARQgfBFgOAXQgOAWgLAAQgVAAg7iKg");
	this.shape_14.setTransform(-90.1,-28.3);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#006E47").s().p("AhKDZQghgIgVgMQgMgHgIgaQgIgaAAghQAAgOAFgHQAGgIAJAAQAOAAAPAbIAHANQATAhAXAPQAXAPAeAAQAhAAAXgTQAWgTAAgdQAAgqhYgnIgKgEQhIgfgYgaQgYgbAAgqQAAg2AogjQAngjBAAAIAjAEIApAJIAMgIIAKgDQAIAAAGAFQAFAFAHALQAKASAGAUQAGAUAAAPQAAAKgFAFQgFAGgIAAQgQAAgPgWIgFgGQgRgWgUgKQgTgLgZAAQghAAgUAQQgTAPAAAbQAAAZAQAQQAQAQBAAcIAMAFQA2AXAYAUQAQAPAJAVQAJAUAAAYQAAA9grAjQgrAihMAAQgkAAghgHg");
	this.shape_15.setTransform(-133,-35.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.sweetinspiration, new cjs.Rectangle(-152.3,-73.2,304.8,146.5), null);


(lib.partyreadyrecipes = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E47").s().p("AgWCcIgggGIgJAGIgKACIgGgCIgGgEQgKgIgIgYQgJgZAAgWQAAgJAFgHQAFgGAIAAQAOAAAOAYIALASQAJAMAQAHQAPAHARAAQAUAAAMgKQALgKAAgRQAAgZgxgYIgSgJQgugXgRgTQgQgTAAgdQAAgnAbgYQAbgZAsAAIAUABIAVAEIAOgGIAKgCQAOAAAOAYQAOAYAAAaQAAAKgEAGQgFAGgJAAQgHAAgGgFQgHgGgJgPQgLgSgMgHQgMgIgRAAQgQAAgLAKQgLAKAAAPQAAAOALALQALAKAlATIADACQBUAoAAAxQAAApggAdQghAcgwAAg");
	this.shape.setTransform(35.1,42.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E47").s().p("AhhBxQgrgsAAhAQAAhGAsgtQAsgtBEAAQA6gBAhAiQAiAgAAA4QAAATgGAGQgFAGgXAAIhyAAQgKAAgFgFQgFgFgBgIQABgIAFgEQAFgEAKAAIA+AAIAPgCQAEgDAAgGQAAgdgUgVQgTgTgbAAQgkAAgRAfQgSAfAAAsQAAAuAZAjQAYAiAlAAQAWAAAPgGQAQgEAOgKIALgIQAPgNAIAAQAGAAAFAFQAEADABAHQAAAHgIALQgHAKgNAKQgaAVgZAKQgYAKgdAAQg/AAgqgsg");
	this.shape_1.setTransform(6.1,42.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E47").s().p("AiRDNQgPgFAAgNQAAgKAMgFIAQgIQAGgGADgYQACgXAAhLIAAgwQgBhSgCgXQgDgYgHgEIgOgFQgSgGAAgKQAAgHAGgGQAFgEANgFIApgNQAUgGALAAQAIAAAEAFQAEAEgBALIAAAPIABAGIACACIAMgJIALgIQASgOARgHQARgGARAAQA5gBAiApQAkApAABBQAABIgnAuQgpAug9AAQgZAAgKgHQgKgIAAgLQAAgHAFgFQAFgFAIABIAIABIAKABQAiAAATgcQAVgcAAgtQgBg0gVgfQgWgfgigBQgeAAgTASQgSASAAAtIAAC+IADAeQABALADAFQAEAEANAEIAMAEIAHAFIACAJQAAALgSAFQgRAFgqgBQgsAAgPgEg");
	this.shape_2.setTransform(-28.8,47.9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E47").s().p("Ag1DWQgPgFAAgNQAAgKAPgFIAIgEQAIgEADgKQADgKAAgXIgBgUIAAgYIAAgfQABgwgDgNQgDgOgFgEIgPgFQgSgGAAgKQAAgGAGgFQAGgGAMgFIAugOIAfgGQAIAAAEAGQADAFAAAOIAAASIgBANIgCBMIAAACIgBBKQAAAcACAMQADAMAHADIALAFQAPAGAAALQABAMgQAFQgOAEgoAAQgsAAgPgFgAgkiXQgNgKgBgQQAAgRAPgMQAOgMAUAAQASAAANALQAOALAAAQQAAARgPALQgNAMgVAAQgTAAgMgLg");
	this.shape_3.setTransform(-54.7,35.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E47").s().p("AhfBxQgqgsAAhAQAAhFAtgtQAtguBCAAQAyAAAjAaQAiAZAAAiQAAAOgJAJQgKAJgPAAQgPAAgKgHQgJgIgKgYQgKgVgLgJQgMgJgSAAQgiAAgTAaQgUAaAAAuQAAA1AcAiQAbAiArAAQAPAAANgFQANgEAMgHIALgJQAQgMAJAAQAHAAADADQAEAEAAAGQAAAHgGALQgHAKgKAJQgXAVgZAKQgaAJgeABQg+AAgrgsg");
	this.shape_4.setTransform(-78.8,42.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E47").s().p("AhhBxQgrgsAAhAQAAhGAsgtQAsgtBEAAQA6gBAhAiQAiAgAAA4QAAATgGAGQgFAGgXAAIhyAAQgKAAgFgFQgFgFgBgIQABgIAFgEQAFgEAKAAIA+AAIAPgCQAEgDAAgGQAAgdgUgVQgTgTgbAAQgkAAgRAfQgSAfAAAsQAAAuAZAjQAYAiAlAAQAWAAAPgGQAPgEAPgKIALgIQAPgNAIAAQAGAAAFAFQAFADAAAHQAAAHgIALQgHAKgNAKQgaAVgZAKQgYAKgdAAQg/AAgqgsg");
	this.shape_5.setTransform(-110.5,42.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E47").s().p("ABACWQgchggVgTQgVgTgeAAQgYAAAAgUQAAgSATAAQAyAAAYgUQAYgTAAgpQAAgngYgUQgYgVgvAAQgXAAgJAEQgJACgDAJIgDAbIgBA8IAACEIACBaQACAVAFAEIAOAGQASAHAAANQAAANgQAFQgRAFgwAAQguAAgRgFQgRgFAAgNQAAgNATgHIANgGQAGgFADgkQADgkAAheIgChwQgDgsgEgGQgDgEgQgHQgQgGAAgMQAAgKAJgGQAJgFATAAIBCAAIA8gBIAwgCQBBAAAjAcQAiAcAAA1QAAAogWAdQgYAdgpAMIAAADQAgAGATAUQASAUAOAwIAIAeQAMAvARAAIAJgBIALAAQAFAAAFAEQAFAFAAAGQAAAOgRAJQgSAJgcAAQg7AAgVhGg");
	this.shape_6.setTransform(-147.6,36);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006E47").s().p("AiKDGQgOgMAAgTQAAgPAKgLQALgLAPABIANABIAJAIIAIAKQAIAMAGAAQAPABAQgWQAPgXAAgXQAAgagVgvIgDgHIgwhpIgbg6QgGgLgRgIQgLgEgDgEQgEgFAAgGQAAgNAQgGQAQgEAsAAQArAAAPAEQAPAFAAAMIgCAJIgFAGIgLAFQgMAEAAAGIAGAWIAYA9IAYA3QAIAPAEAAQADAAAHgOIAUgvIAWg8QAHgVAAgIQAAgJgRgJQgRgJAAgIQAAgLAOgEQAOgEAiAAQAkAAAMAEQANAFAAAMQAAALgRAEIgMAEQgRAKgUAzIgIAXIgnBgQgxB8gfAnQggAkgsABQgWAAgOgNg");
	this.shape_7.setTransform(154.4,-22.7);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006E47").s().p("AiDC2QgjgpAAhBQAAhJAogtQApguBAAAIAVACQAJADAFAHQAFAHAAAHQAAAQgTAAIgJgBIgIAAQghAAgUAbQgUAbAAAvQAAAzAWAfQAWAgAhgBQAfABASgSQARgRAAghIAAhSIAAiLQAAgVgEgHQgEgJgLgEIgIgCQgTgFAAgLQAAgIAIgGQAHgFAXgJIAhgKIAcgDQAKAAAFAGQAEAGAAANIAAAPIgDC5IACB9QACAdAEAEIAVAHQAQAEAAAKQAAAOgrAOIgeAIIgXACQgJAAgDgEQgEgFAAgKIAAgPIgBgFIgBgCIgKAGIgNAKQgSAOgQAGQgRAGgTAAQg4AAgjgog");
	this.shape_8.setTransform(122.1,-35.4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006E47").s().p("AA1CNIgQgQIgNAHQglAZgkAAQgsAAgbgaQgbgZAAgqQAAgwAigZQAjgbA/AAQAPAAAHAEQAIAEAAAMQAAARgVAAQgdAAgSAOQgSAPAAAZQAAAYAPAOQAQAPAbAAQAcAAANgNQAMgNAAggIAAhxQAAgagMgPQgLgOgUAAQgPAAgNAHQgMAGgMANIgHAIQgSAXgUAAQgMAAgHgHQgHgIAAgNQAAgcAjgTQAjgUA2AAQAhAAAYAJQAYAJANARQAJALAEASQADATAAArIAABgQAAARADAIQADAIAGACIAJADQATAFAAAKQAAAOgUAMQgUAMgbAAQgNAAgPgQg");
	this.shape_9.setTransform(87.2,-28.7);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006E47").s().p("AhhBxQgrgsAAhBQAAhFAsgtQAsguBDAAQA7AAAiAiQAhAgAAA5QAAASgFAGQgGAGgWAAIhzAAQgKAAgFgFQgGgFAAgIQAAgIAGgEQAFgFAKAAIA+AAIAPgCQAEgCAAgHQAAgdgTgTQgUgUgaAAQglAAgRAfQgRAgAAArQgBAuAYAiQAYAjAlgBQAXAAAPgEQAPgFAPgKIALgJQAPgMAIAAQAGAAAFAEQAEAEAAAGQAAAIgHAKQgIALgNAKQgaAWgYAJQgYAJgcAAQhAAAgqgrg");
	this.shape_10.setTransform(54.6,-28.7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006E47").s().p("ABACWQgchggVgTQgVgTgeAAQgYAAAAgUQAAgSATAAQAyAAAYgUQAYgTAAgpQAAgngYgUQgYgVgvAAQgXAAgJAEQgJACgDAJIgDAbIgBA8IAACEIACBaQACAVAFAEIAOAGQASAHAAANQAAANgQAFQgRAFgwAAQguAAgRgFQgRgFAAgNQAAgNATgHIANgGQAGgFADgkQADgkAAheIgChwQgDgsgEgGQgDgEgQgHQgQgGAAgMQAAgKAJgGQAJgFATAAIBCAAIA8gBIAwgCQBBAAAjAcQAiAcAAA1QAAAogWAdQgYAdgpAMIAAADQAgAGATAUQASAUAOAwIAIAeQAMAvARAAIAJgBIALAAQAFAAAFAEQAFAFAAAGQAAAOgRAJQgSAJgcAAQg7AAgVhGg");
	this.shape_11.setTransform(17.5,-35.2);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#006E47").s().p("Ag7AfQgJAAgEgDQgEgEAAgIIADgNIAHgRQAEgJAEgDQAEgCANAAIAOAAIAbAAIAzgCIAIAAQAJAAAFADQAEAEAAAIQAAAQgJAOQgKAPgOAAIgOgBIgRgBIhCADIgGAAg");
	this.shape_12.setTransform(-15.3,-29.1);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#006E47").s().p("AiKDGQgOgMAAgTQAAgPAKgLQALgLAPABIANABIAJAIIAIAKQAIAMAGAAQAPABAQgWQAPgXAAgXQAAgagVgvIgDgHIgwhpIgbg6QgGgLgRgIQgLgEgDgEQgEgFAAgGQAAgNAQgGQAQgEAsAAQArAAAPAEQAPAFAAAMIgCAJIgFAGIgLAFQgMAEAAAGIAGAWIAYA9IAYA3QAIAPAEAAQADAAAHgOIAUgvIAWg8QAHgVAAgIQAAgJgRgJQgRgJAAgIQAAgLAOgEQAOgEAiAAQAkAAAMAEQANAFAAAMQAAALgRAEIgMAEQgRAKgUAzIgIAXIgnBgQgxB8gfAnQggAkgsABQgWAAgOgNg");
	this.shape_13.setTransform(-40.7,-22.7);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#006E47").s().p("AgQC0QgPgFgKgJQgLgKgEgRQgFgQAAgtIAAigIgbAAIgJgDIgCgHIAAgIQAAgJAfgbIAMgLIAMgKQAfgbALAAIAJACQADADAAAEIAAA5IBEAAQAHAAADACQADADAAAJIAAAHQAAAIgDADQgEAEgGAAIg+AAIgFACIgCAHIAACUQAAAnAHAKQAGAKASAAQAJAAAPgFIAVgFQAGAAAFAEQAEAEAAAGQAAAQgZAQQgaAPggAAQgSAAgPgFg");
	this.shape_14.setTransform(-66.8,-31.6);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#006E47").s().p("AhbCVQgOgFAAgNQAAgKAOgGIAIgDQAIgEADgLQAEgKAAgWIgBgVIAAgYIAAgRQAAg3gDgRQgCgQgHgEIgNgFQgSgGAAgKQAAgHAFgFQAGgFANgGIAogNIAbgFQAPAAAEApIABAGIADABQAPgYAQgNQARgNASAAQAUAAANANQAMAMAAAVQAAAVgJAMQgKAMgRAAIgQgDIgMgJIgHgLQgDgIgEAAQgUAAgIAdQgIAcAABbQABAaACANQADANAJAEIALAEQATAGgBAMQAAALgQAFQgRAFgoAAQguAAgPgFg");
	this.shape_15.setTransform(-88.7,-29);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#006E47").s().p("AA1CNIgQgQIgNAHQglAZgkAAQgsAAgbgaQgbgZAAgqQAAgwAigZQAjgbA/AAQAPAAAHAEQAIAEAAAMQAAARgVAAQgdAAgSAOQgSAPAAAZQAAAYAPAOQAQAPAbAAQAcAAANgNQAMgNAAggIAAhxQAAgagMgPQgLgOgUAAQgPAAgNAHQgMAGgMANIgHAIQgSAXgUAAQgMAAgHgHQgHgIAAgNQAAgcAjgTQAjgUA2AAQAhAAAYAJQAYAJANARQAJALAEASQADATAAArIAABgQAAARADAIQADAIAGACIAJADQATAFAAAKQAAAOgUAMQgUAMgbAAQgNAAgPgQg");
	this.shape_16.setTransform(-117,-28.7);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#006E47").s().p("AibDVQgRgGAAgMQAAgNASgHIAOgGQAGgFADglQACgjABheIgChxQgEgrgDgGQgDgEgQgHQgQgGAAgMQAAgKAJgGQAJgFATgBIAfAAIAiABIA9gCIAwgBQBDAAAiAdQAhAcAAA6QAAA+gpAhQgqAhhPgBQgeAAgBgTQAAgWAaAAQAmAAAYgTQAWgUAAgsQAAgqgXgTQgYgUgwAAQgWAAgJADQgJAEgDAJIgDAbIgCA+IAACEIADBVQABAXAGAEIAOAGQASAHAAANQAAAMgRAGQgQAFgwAAQguAAgRgFg");
	this.shape_17.setTransform(-150.9,-35.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.partyreadyrecipes, new cjs.Rectangle(-171.8,-73.2,343.6,146.5), null);


(lib.mainbutton = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006F46").s().p("EgQFAzRMAAAhmhMAgLAAAMAAABmhg");
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.kalelogo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgeAfQgNgNAAgSQAAgRANgNQANgNARAAQASAAANANQANANAAARQAAASgNANQgNANgSAAQgRAAgNgNgAgYgYQgKAKAAAOQAAAQAKAKQAKAKAOAAQAPAAAKgKQAKgKAAgQQAAgOgKgKQgKgKgPAAQgOAAgKAKgAAMAZIgOgVIgFAAIAAAVIgJAAIAAgzIATAAQARAAAAAPQAAANgNABIAPAWgAgHgDIAGAAQANAAAAgIQAAgHgMAAIgHAAg");
	this.shape.setTransform(54,24.5,0.414,0.414);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AjnEaQgUgDgIgEQgJgFAAgNQAAgKAGgHQAFgHAJAAIARAAQAKAAAFgLQADgKgBgXIAAl5QABgXgDgKQgFgLgKAAIgRAAQgJAAgFgHQgGgHAAgKQAAgNAJgFQAIgEAUgDQBegNBrAAQBNAAA1ASQA1ASAnAoQAlAlAVA5QATA4AABEQAABNgZA9QgZA+gwAlQglAegvAOQgxAOhEAAQhrAAhegNgAgvjrQgcAFgKALQgKAMAAAhIAAFjQAAAhAVALQANAHAnADQBNAEAshAQAqg/ABhwQAAhwgrg/Qgrg/hKAAIgdADg");
	this.shape_1.setTransform(25.8,12.5,0.414,0.414);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgNBlQgFgDAAgHIAAiTQAAgKgMAAIgyAAQgKAAAAgPIABgNQACgIAHAAICfAAQAMAAAAASQAAASgLAAIgyAAQgMAAAAAKIABCTQAAAHgFADQgEACgKAAQgJAAgEgCg");
	this.shape_2.setTransform(33.7,36.6,0.414,0.414);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhMBmQgNAAAAgPIAAiuQAAgOANAAICbAAQAGAAADAFQACADAAAJQAAAKgCADQgDAGgHAAIh5AAQgIAAAAAJIAAAbQAAAKAKAAIBFAAQALAAAAASQAAAQgKAAIhFAAQgLAAAAALIAAAeQAAAKAKAAIB4AAQAKAAAAATQAAARgKAAg");
	this.shape_3.setTransform(21.7,36.6,0.414,0.414);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAxBgIhAhGQgLgJgTAAQgFAAgEAEQgDAFAAAGIAAA8QAAAMgVAAQgRAAAAgNIAAi0QAAgIAFgCQAEgCALAAQASAAAAAMIAAA3QAAANAJAAQALAAAFgDQAEgBAFgFIBJhDQANgLAMAMQAMALgKAKIhAA6QgJAIAJAJIBOBWQAIAIgGAFQgFAFgNAAQgTAAgHgIg");
	this.shape_4.setTransform(9.4,36.6,0.414,0.414);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAvBeIghgxQgFgJgKAAIgtAAQgEAAgDADQgDACgBAFIABAwQAAAHgKACIgPAAQgNAAAAgLIAAi6QAAgIAJAAIBrAAQAgAAAUASQAVAUgBAgQAAAXgOAPQgIAJgPAJQgHAIAEAFIAiAyQAFAHgFAFQgEAEgPAAQgRAAgFgJgAg5g4IAAAuQABAFAEADQAEACAFAAIA+AAQAQAAALgHQALgKAAgPQAAgRgLgJQgLgJgQAAIg+AAQgOAAAAALg");
	this.shape_5.setTransform(-4.6,36.6,0.414,0.414);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("ABCBgIgOgbQgCgHgHAAIhTAAQgJAAgEALIgMAXQgDAHgSAAQgWAAAFgMIBZi4QAFgKAKAAQALAAAFAJIBXC6QADAGgJAEQgGACgIAAQgPAAgDgIgAgEgdIgYAyQgDAIAIAAIAwAAQABAAABAAQAAgBABAAQABAAAAAAQAAgBABAAQACgCgCgDIgZgzQgBgDgEAAQgCAAgCADg");
	this.shape_6.setTransform(-18.4,36.6,0.414,0.414);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("ABZBlQgFgDAAgFIgOhrQgCgHgFAAQgDAAgDAEIgxA+QgEAFgFAAQgHAAgEgHIgtg7QgCgDgEAAQgFAAgBAHIgOBpQgCAKgTAAQgGAAgFgCQgGgDAAgGIAVixQACgJADgCQAEgFALAAQAKAAAFAIIA4BPQAFAIAEAAQAEAAAHgIIA7hQQAEgIALAAQAGAAADACQAEADACAJIAVC1QABAKgXAAQgFAAgFgCg");
	this.shape_7.setTransform(-32.4,36.6,0.414,0.414);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AipF/QhPhTAAiLQAAhZAghEQAghCA6gnQAZgTAmgTQAmgTAngOQAKgDgDgJQgCgKgNADQg7ALgrgSQgWgJgdgRQghgUgJgEQgvgWg6AZQgVAJgMgLQgLgLAGgXQAXhWBDg3QBKg9BQAXQA0APAlA0QAmA2AfALQATAGgBAPQAAAOgRADQgaAFgjgRQgggPgdgbQgfgcgvgCQgsgCgbAVQgLAIADAHQAEAHAKgDQAggHAdAGQAoAIAbAgQAkAoAuAPQA4ASAugfIAZgWQANgNAMAEQAPAEgBAUQgBAUgTAZQgiAsg+AeQhFAjgeAdQgwAwgTA9QgPAzAABQQAAByAqBAQAqBABKAAQBKAAArhCQAqhBAAhwQAAhfgXg4QgZg6g2gVQgbgKAFgTQAFgUAhgEQA3gGA8AsQBoBOAACjQAACOhPBVQhQBUiHAAQiDAAhPhUg");
	this.shape_8.setTransform(6.1,-22.5,0.414,0.414);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("ABnDxQhFg2gYheIgBgDQgCgLgHABQgGgBgCALIgBABQgYBghGA2QhIA2hoAAQh+AAhMhQQhMhRAAiFQAAiGBMhRQBLhQCAAAQBpAABHA2QBHA3AXBgQACALAGgBQAHAAACgLIABAAQAXhgBGg2QBHg2BoAAQB/AABNBPQBMBQAACGQAACHhMBRQhNBQiBAAQhmAAhHg2gACniqQgpA/AABtQAABtApA9QAoA+BIAAQBGAAApg/QAphAAAhrQAAhqgqhAQgpg/hHAAQhGAAgoA/gAmFiqQgoA/AABtQAABtAoA9QAoA+BIAAQBGAAApg/QAphAAAhrQAAhqgqhAQgpg/hHAAQhGAAgoA/g");
	this.shape_9.setTransform(-8.7,12.5,0.414,0.414);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("Ai5EbQgWAAgJgFQgIgFAAgOQAAgKAGgHQAHgHAJAAIARAAQAKAAAEgLQADgJAAgYIAAl7QAAgXgDgKQgCgGgEgDQgEgEgEAAIgRAAQgJAAgHgHQgGgHAAgJQAAgOAJgGQAIgFAWAAIFvAAQAaAAAEAVIAMA7QAEAQgFAJQgFAJgMAAQgPAAgHgOQgEgFgFgNQgFgQgPgFQgNgEggAAIhtAAQghAAgJAJQgIAJAAAiIAABkQAAAaAIAFQAFADAdAAIBFAAQAbAAAIgDQAHgDACgNIAAgFQAEgWATAAQAOAAAFAJQAFAJAAAWIAABHQAAAWgFAJQgFAJgOAAQgTAAgEgXIAAgFQgCgNgIgDQgHgEgbAAIhFAAQgeAAgEAEQgIAFAAAZIAACLQAAAbACAGQAGALAMAAIATAAQAKAAAGAHQAGAHAAAKQAAAOgJAFQgIAFgYAAg");
	this.shape_10.setTransform(-40.8,12.5,0.414,0.414);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AhTEbIgTgEQgIAAgKAJQgKAIgJAAQgLAAgGgHQgGgGgEgQIgVhUQgCgIAAgJQAAgMAHgIQAIgHAMAAQAMAAAJALIAMARQAWAfAhASQAiASAkAAQApAAAagVQAZgUAAgiQAAghgbgfQgbgdg/gsIhNg2QgSgPgTgWQgggmAAgzQAAg9ArgmQArgmBGAAQAlAAAjAIIAWAFIALACQAJAAALgIQAKgHAIAAQASAAAGAYIAUBcQABAEAAAIQAAAIgHAGQgHAGgKAAQgMAAgLgOQgNgVgHgIQgGgGgOgLQgjgbgtAAQgcAAgSAPQgRAQAAAaQAAAXAJALQAMASAbAWIApAdQAzAkAWARQAXASAUAUQAWAWAMAfQAMAeAAAhQAABJgyAtQgzAthUAAQgzAAglgNg");
	this.shape_11.setTransform(45.6,12.5,0.414,0.414);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("Ah+EYQgLgJgHgYIhJjYQgBgFgEAAQgFAAgBAFIhNDYQgKAagHAIQgNAIgQABQgTgBgKgIQgLgKgJgYIimm+QgKgZgHgIQgHgHgUgFQgOgBgFgGQgFgFAAgKQAAgXAdAAICvAAQAcAAAAAXQAAAMgHAEQgHAFgRABQgOACgGAEQgGAFAAALQAAAIADALIBzFGQACAFAFAAQAEgBACgFIA/i1QAIgZgHgYIglhuQgEgJgHgFQgGgEgPgEQgNgEgGgEQgFgGAAgJQAAgaAdAAICnAAQAdAAAAAXQAAATgcAFQgRABgFAFQgGAFAAALQAAALAIAZIBfEsQACAFAEAAQAFgBABgFIBdk6QAEgLAAgJQAAgTgdgDQgbgCAAgWQAAgMAHgGQAIgGARAAIElAAQAVAAAIAGQAIAFAAAOQAAAKgGAHQgGAHgJAAIgQAAQgLAAgFAKQgCAJAAAZIAABuQAAAdAFAHQAGAGAXAAIB0AAQAXAAAHgHQADgEAAgGIABgfIAAhoQAAgbgDgHQgFgKgKAAIgQAAQgKAAgHgHQgGgHAAgKQAAgOAIgFQAJgGAWAAICaAAQAWAAAJAGQAJAFAAAOQAAAKgHAHQgGAHgJAAIgSAAQgEAAgEADQgFAEgBADQgDAKAAAYIAAF8QAAAYADALQABADAFAEQAEACAEAAIASAAQAJAAAGAIQAHAGAAAKQAAAOgJAGQgIAEgXAAIiaAAQgWAAgIgEQgIgGAAgOQAAgKAGgGQAHgIAJAAIAQAAQAKABAFgKQADgIAAgbIAAh8IgBgdQAAgHgDgDQgHgIgXAAIh0AAQgXAAgGAHQgFAGAAAeIAACAQAAAZACAKQAFAKALgBIAQAAQAJAAAGAIQAGAGAAALQAAANgIAGQgIAEgVAAIiaAAQgWAAgJgEQgIgGAAgOQAAgKAGgGQAHgIAJAAIARAAQAEAAAFgCQAEgEABgDQADgIAAgbIAAl8QAAgwgkAEQgLABgHAJQgIAKgGAVIiHGzQgJAfgKAMQgLAKgTABQgTAAgLgKg");
	this.shape_12.setTransform(-30.9,-15.2,0.414,0.414);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AihEbQgWAAgIgFQgIgGAAgOQAAgJAGgHQAGgGAJAAIARAAQAEAAAEgEQAEgDACgEQADgIAAgXIAAmAQAAgZgDgHQgDgMgLAAIgRAAQgKABgGgHQgHgHAAgKQAAgOAJgFQAJgGAWAAICcAAQAWAAAJAGQAJAFAAAOQAAAKgGAHQgHAHgJgBIgSAAQgOAAgDAMQgDAFAAAbIAAFkQAAAdACAJQACAJAIAFQAGAFALABQALACAaAAIAwAAQAvAAAPggIAIgQQAIgPAPAAQAMgBAFAJQAFAJgEAQIgNBCQgEAVgaAAg");
	this.shape_13.setTransform(28.7,-15.5,0.414,0.414);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AjREWQgIgGAAgOQAAgJAGgHQAGgGAJAAIARAAQAEAAAEgEQAEgDABgEQAEgIAAgaIAAl7QAAgZgEgIQgBgGgEgDQgEgEgEAAIgRAAQgJAAgHgHQgGgHAAgKQAAgNAJgGQAIgFAWAAIFSAAQAZAAAFAVIAMA7QADAQgFAJQgFAIgMAAQgPAAgGgNQgDgCgGgQQgGgQgPgFQgMgEggAAIhQAAQghAAgJAJQgIAJAAAiIAABkQAAAaAIAFQAEADAeAAIAmAAQAbAAAIgDQAHgDACgNIAAgFQAEgWATAAQAOAAAFAJQAFAJAAAWIAABHQAAAWgFAJQgFAIgOAAQgTAAgEgWIAAgFQgCgNgIgDQgHgEgbAAIgmAAQgeAAgEAEQgIAFAAAZIAABsQAAAiADALQADALAKAEQAPAFAiAAIBVAAQAvAAAPgfIAHgQQAIgQAPAAQAMAAAFAJQAFAJgDAQIgNBCQgFAVgaAAIlhAAQgWAAgIgFg");
	this.shape_14.setTransform(47.4,-15.4,0.414,0.414);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#0C6E47").s().p("AqoZMQk7iEjyjzQjxjxiFk6QiKlGAAljQAAljCKlGQCFk6DxjzQDzjxE6iFQFFiKFjAAQFkAAFFCKQE7CFDxDxQDyDzCFE6QCKFGAAFjQAAFjiKFGQiFE6jyDxQjxDzk7CEQlFCKlkAAQljAAlFiKg");
	this.shape_15.setTransform(0,0,0.414,0.414);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.kalelogo, new cjs.Rectangle(-72.5,-72.5,145,145), null);


(lib.holidaytipsrecipes = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E47").s().p("AhSBgQglgmAAg2QAAg6AlgnQAmgnA5AAQAxAAAdAcQAdAdAAAvQAAAPgFAFQgFAFgTABIhhAAQgJAAgEgFQgFgDABgHQgBgHAFgEQAEgEAJAAIA1AAIAMgCQADgCAAgFQAAgYgQgRQgRgRgWAAQgfAAgPAbQgOAaAAAlQAAAnAVAdQAUAdAfAAQATAAANgEQAMgEANgJIAJgHQANgLAHAAQAGABADADQAEAEAAAFQAAAGgGAJQgHAJgKAIQgXASgUAJQgVAIgYAAQg1gBgkgkg");
	this.shape.setTransform(176.3,36.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E47").s().p("AhMB+QgNgEAAgLQAAgJAMgEIAHgDQAHgEACgIQADgJAAgTIAAgRIAAgVIAAgPQAAgugCgOQgCgOgGgDIgMgFQgPgFAAgIQAAgGAFgEQAEgFAMgEIAigLIAXgFQAMAAAEAjIABAFIABABQANgVAPgLQAOgKAOAAQASAAAKAKQALALAAASQAAASgIAKQgIAKgPAAIgNgDIgKgHIgGgKQgDgHgDAAQgRAAgHAZQgGAYAABMQAAAWACAMQADALAHADIAKADQAPAFAAAKQAAAKgOAEQgOAEgiAAQgnAAgMgEg");
	this.shape_1.setTransform(153.3,35.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E47").s().p("AhcBfQgkglAAg5QAAg5AmglQAmgnA4AAQA3AAAjAkQAjAjAAA4QAAA7glAnQgmAog3AAQg3AAgkgmgAgwhLQgPAVgBAiQABAxAVAiQAWAiAdAAQAZAAAPgVQAQgVAAgjQAAgwgWgiQgVgigdAAQgZAAgQAVg");
	this.shape_2.setTransform(128.4,36.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E47").s().p("ABfCzQgOgFAAgKQAAgLAQgGIALgGQAFgDABgLQACgLAAgjIAAgNIAAhrIgChAIgfBTQhLDDgQAAQgJAAgOgaQgPgcgjhSIg4iAIgCBlIgBBEIABAvQACAMAEACIALAGQAQAGAAALQAAAKgNAFQgNAEgfABQgcAAgNgGQgMgEAAgLQAAgJAOgGQAOgHABgFQAEgNAEhBQADhBAAhPIAAgIQAAgcgCgIQgCgKgGgDIgMgFQgQgHAAgKQAAgKALgEQALgDAlgBIAkABIALACQAEAEASAuIAPAkIAIASQA9CXAFABQAFgBAXg2QAWg2AghZIAFgQQAJgcAIgIQAEgFAKgCIAjgCQAiABALADQAMAEAAAKQAAALgPAFIgHADQgHAEgDALQgCAJAAAnIACCRQADBBACAJQABAGAMAEIAFACIAKAHQADADAAAGQAAAKgOAFQgOAEgqABQgmgBgOgEg");
	this.shape_3.setTransform(90.7,30.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E47").s().p("AiZCaQgvgkAAg8QAAggAPgZQAPgZAhgWIABgDQgLgLgFgMQgGgNAAgNQAAgoAegZQAdgaAuAAQAfAAAWAMQAVAMAAAQQAAAGgFAEQgFAEgHAAIgVgHQgSgGgOAAQgVAAgMANQgMAOAAAWQAAAKADAHQADAHAHAGQAGAGALAFIAPAGIAFACIACAEQAAAGgJAKQgKAKgIAAIgLgCIgRgGQgPAMgHASQgIASAAAXQAAAwAgAfQAgAgAxAAQApAAAagVQAZgWAAgiQAAgWgLgMQgKgNgRAAQgSAAgLAKQgLALAAAQIAAAFIAAACIgEACIgEAAQgJAAgFgHQgGgHAAgMQAAglBwg0IAHgDQAdgOAQgPQAPgRAAgRQAAgMgHgGQgGgFgOgBIgJACIgKABQgFAAgEgEQgDgDAAgGQAAgLAOgIQAOgHAVAAQAbAAAQAPQAQAPAAAaQAAAfgbAaQgbAag5AVQAXAJANATQAMAUAAAZQAAAUgIASQgHASgPAPQgXAagjANQgjAMgsAAQhOAAgugkg");
	this.shape_4.setTransform(32.5,30.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E47").s().p("AgSCEIgbgFIgIAFIgIACIgFgBIgFgEQgJgHgHgVQgIgUAAgTQAAgIAFgGQAEgFAGAAQANAAAMAUIAJAQQAIAKANAGQANAFAOAAQARABAJgJQALgIgBgOQABgWgrgUIgOgIQgogTgNgQQgPgRAAgXQAAgiAYgUQAXgWAlAAIARABIASAEIAMgFIAIgCQAMABAMATQAMAUAAAWQAAAJgFAGQgDAEgIAAQgFAAgGgEQgFgFgJgMQgJgQgKgGQgLgHgOABQgOgBgIAJQgKAIABAOQAAALAJAJQAJAJAfAQIADABQBGAjABApQAAAjgbAYQgcAXgpABg");
	this.shape_5.setTransform(-16.2,36);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E47").s().p("AhSBgQgkgmAAg2QgBg6AmgnQAlgnA5AAQAxAAAdAcQAcAdAAAvQABAPgFAFQgFAFgTABIhhAAQgIAAgFgFQgFgDAAgHQAAgHAFgEQAFgEAIAAIA0AAIAOgCQACgCAAgFQAAgYgQgRQgRgRgWAAQgeAAgPAbQgPAaAAAlQAAAnAUAdQAUAdAgAAQATAAANgEQAMgEANgJIAJgHQANgLAHAAQAFABAFADQADAEAAAFQAAAGgHAJQgGAJgKAIQgWASgVAJQgUAIgZAAQg1gBgkgkg");
	this.shape_6.setTransform(-40.9,36.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006E47").s().p("Ah7CtQgNgEAAgKQAAgJALgFIANgGQAFgFACgUQACgUAAhAIAAgoQAAhFgCgUQgDgUgFgEIgMgEQgPgFAAgJQAAgFAEgFQAEgFALgDIAkgMQAQgEAKAAQAGAAAEAEQADAEAAAIIAAANIAAAFIACABIAKgGIAJgHQAQgMANgGQAPgGAPAAQAvAAAeAjQAeAjAAA3QAAA8ghAnQgiAog0AAQgWgBgHgGQgJgGAAgKQgBgGAFgEQAEgEAHAAIAHACIAIABQAdAAAQgYQARgYAAgnQAAgqgSgbQgTgbgcAAQgaAAgPAPQgPAOgBAnIAAChIACAaQABAKADADQADADAMADIAKAEIAFAFIADAHQAAAKgQADQgOAFglAAQgkAAgNgFg");
	this.shape_7.setTransform(-70.5,40.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006E47").s().p("AgsC2QgNgFAAgLQAAgIANgFIAGgDQAGgDADgJQADgIAAgUIAAgRIAAgUIAAgbQgBgogCgLQgCgMgEgDIgNgEQgPgFAAgJQAAgFAFgFQAEgEAMgFIAmgMIAagFQAHAAADAFQADAFAAAMIAAAPIgBALIgCBAIAAACIgBA+QAAAYACAKQADAKAFADIAKAEQANAFAAAKQAAAKgNAEQgMAEghAAQgmAAgMgEgAgfiAQgLgIABgOQgBgOAMgKQAMgLARAAQAQAAALAKQALAJAAAOQAAAOgMAKQgMAJgRAAQgQAAgLgJg");
	this.shape_8.setTransform(-92.6,30.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006E47").s().p("AhQBgQgkgmAAg2QAAg6AmgmQAngoA4AAQApAAAeAXQAdAVAAAdQAAAMgIAIQgJAHgMAAQgNAAgIgGQgIgGgIgVQgIgSgKgHQgKgIgPAAQgdAAgQAXQgRAVAAAnQAAAtAXAdQAYAcAjAAQANAAAMgEQALgDAJgHIAKgHQAOgLAIAAQAFAAADAEQADADAAAFQAAAHgGAIQgEAJgJAHQgUASgWAJQgVAHgZABQg1gBgkgkg");
	this.shape_9.setTransform(-113,36.1);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006E47").s().p("AhSBgQgkgmAAg2QAAg6AlgnQAlgnA5AAQAxAAAdAcQAdAdgBAvQABAPgFAFQgFAFgTABIhhAAQgIAAgFgFQgEgDgBgHQABgHAEgEQAFgEAIAAIA0AAIAOgCQADgCAAgFQAAgYgRgRQgRgRgWAAQgeAAgPAbQgPAaAAAlQAAAnAUAdQAVAdAfAAQATAAANgEQAMgEANgJIAJgHQANgLAHAAQAGABAEADQADAEAAAFQAAAGgHAJQgGAJgLAIQgVASgVAJQgUAIgZAAQg1gBgkgkg");
	this.shape_10.setTransform(-140,36.1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006E47").s().p("AA3B/QgYhRgSgQQgSgRgaAAQgUAAAAgQQAAgQARAAQAqAAAUgQQAUgQAAgjQAAgigUgRQgVgRgnAAQgUAAgHADQgHACgDAIIgDAWIgBAzIAABwIACBMQABASAFAEIAMAFQAPAGAAAKQAAALgOAFQgOAEgoAAQgoAAgOgEQgOgFAAgLQAAgKAQgGIALgGQAFgEADgeQACgeAAhQIgChgQgCglgEgEQgCgEgOgGQgNgFAAgKQAAgJAIgEQAHgFAQAAIA4AAIAzgBIAogBQA4AAAdAYQAdAXAAAtQAAAigTAYQgUAZgjAKIAAADQAcAFAPARQAQAQAMApIAHAaQAJAnAPAAIAIAAIAJgBQAEAAAEAEQAEAEAAAFQAAAMgOAIQgPAHgYAAQgyAAgRg7g");
	this.shape_11.setTransform(-171.5,30.5);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#006E47").s().p("AgbBOQgFgDAAgEIAFgKIAFgHIAPgcQAGgNAAgFIgCgHIgJgEQgNgFgGgKQgGgIAAgOQAAgRAKgLQALgLAQAAQAQAAALAPQALAPAAAWQAAARgGASQgHASgRAbIgNAVQgGAGgEAAQgHAAgFgCg");
	this.shape_12.setTransform(114.2,-11);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#006E47").s().p("AgTCEIgbgFIgHAFIgIACIgFgBIgFgEQgJgHgHgVQgHgUAAgTQAAgIAEgGQAEgFAHAAQAMAAALAVIAKAPQAHAKAOAGQANAFAOAAQARABAKgJQAKgIAAgOQgBgWgqgUIgOgIQgngTgOgQQgOgRAAgXQAAgiAXgUQAWgWAlAAIARABIASAEIANgFIAHgCQANABAMATQAMAVgBAWQAAAJgDAEQgFAGgGgBQgHAAgFgEQgFgFgIgMQgKgQgKgGQgKgHgPAAQgNAAgKAJQgIAIgBAOQAAALAKAJQAJAJAfAQIADABQBGAjAAAoQAAAkgbAYQgbAXgoABg");
	this.shape_13.setTransform(95.1,-24.4);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#006E47").s().p("Ah7CtQgNgEAAgKQAAgJALgFIANgGQAFgFACgUQACgUAAhAIAAgoQAAhFgCgUQgCgUgHgEIgLgEQgQgFAAgJQAAgFAFgFQAFgFAKgDIAkgLQARgFAIAAQAIAAADAEQADAEAAAIIAAANIABAFIABABIAJgGIAKgHQAQgMAOgGQAOgFAPgBQAwAAAdAjQAfAjAAA3QAAA8giAnQgiAog0AAQgWgBgIgFQgJgHAAgKQABgGAEgEQAEgEAIAAIAGACIAJABQAcgBARgXQARgYAAgnQgBgqgSgbQgSgbgdAAQgaAAgPAPQgPAPAAAmIAAChIABAaQABAKAEADQADAEALACIAKAEIAGAFIABAHQABAKgQADQgPAFgjAAQglAAgNgFg");
	this.shape_14.setTransform(68,-19.8);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#006E47").s().p("AgtC2QgMgFAAgLQAAgIAMgFIAHgDQAHgDADgJQACgIAAgUIAAgRIAAgUIAAgbQAAgogCgLQgDgMgFgDIgLgEQgQgFAAgJQAAgFAFgFQAEgEALgFIAngMIAagFQAHAAADAFQADAFAAAMIAAAPIAAALIgCBAIAAACIgBA+QAAAYACAKQACAKAGADIAJAEQANAFAAAKQAAAKgMAEQgNAEghAAQgmAAgNgEgAgeiAQgMgIAAgOQAAgOANgKQAMgLARAAQAPAAALAKQALAJAAAOQAAAOgMAKQgMAJgQAAQgRAAgKgJg");
	this.shape_15.setTransform(46,-30.1);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#006E47").s().p("Ag1C1QgOgFAAgLQAAgKAOgFQANgGADgDQADgFABgpIACh4IgBhDIgCgpQgBgHgEgCQgFgCgKAAIgLAAQgSAAgJAEQgKAEgHAKIgIARIgIARIgHAIQgFADgEAAQgIAAgDgGQgEgHAAgQQAAghAIgVQAIgUAMAAIADAAQAUADAfAAICVAAQAfAAAUgDIADAAQAMAAAIAUQAIAVAAAhQAAAQgEAHQgDAGgIAAIgJgDIgHgIIgIgRIgIgRQgHgKgKgEQgKgEgRAAIgLAAQgKAAgEACQgFACgBAHIgCApIgBBDIACB4QABApADAFQADADANAGQAOAFAAAKQAAALgOAFQgPAEgnAAQgnAAgOgEg");
	this.shape_16.setTransform(21.9,-30.1);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#006E47").s().p("Ah1CoQgMgKAAgRQAAgMAJgJQAJgKANABIALABIAIAGIAGAKQAHAKAFAAQANAAAOgTQANgTgBgUQAAgWgSgoIgCgGIgphZIgXgxQgEgJgPgGQgKgEgDgEQgCgDAAgGQAAgLANgEQANgFAlABQAmAAAMADQANAFAAAKIgCAIIgFAEIgJAFQgKAEAAAEIAGATIAUAzIAUAwQAHAMADAAQADAAAGgMIAQgoIATgyQAGgTAAgGQAAgHgOgJQgOgHAAgHQAAgJALgEQALgDAeAAQAeAAALADQAKAFAAAKQAAAJgOAEIgKAEQgPAHgQArIgIAUIggBRQgpBqgbAgQgbAgglgBQgSABgNgLg");
	this.shape_17.setTransform(-21.9,-19.2);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#006E47").s().p("AAtB4IgNgOIgLAGQggAVgfAAQglAAgXgWQgXgVAAgjQAAgpAegWQAdgXA1AAQANAAAGAEQAHAEAAAKQAAAOgSAAQgZAAgPAMQgPAMAAAWQAAAUANAMQANAMAXAAQAYAAAKgLQALgLAAgaIAAhgQAAgXgKgMQgKgMgRAAQgMAAgLAGQgLAFgKAMIgFAGQgPAUgSAAQgKAAgGgHQgGgGAAgLQAAgYAegQQAdgRAvAAQAbAAAUAIQAVAHALAOQAHAKAEAQQADAPAAAlIAABRQAAAOACAHQADAHAFACIAIACQAQAEAAAJQAAAMgRAKQgSAKgWAAQgLAAgNgNg");
	this.shape_18.setTransform(-48.5,-24.3);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#006E47").s().p("AhvCaQgegiAAg3QAAg/AjglQAignA2gBIASACQAIADAEAFQAFAGAAAHQAAANgRAAIgHgBIgHAAQgcAAgRAYQgRAVAAApQAAArATAaQASAbAdAAQAaAAAOgOQAPgPAAgdIAAhGIAAh0QAAgSgDgHQgEgGgJgEIgHgCQgPgFAAgIQAAgIAGgEQAGgFATgHIAcgIIAYgDQAJAAAEAFQADAEAAAMIAAANIgDCcIACBrQACAYAEADIARAGQAOADAAAJQAAAMglALIgZAHIgUACQgHAAgDgEQgDgDAAgJIAAgNIgBgEIgBgCIgIAFIgLAJQgPALgOAGQgPAFgPAAQgwAAgegig");
	this.shape_19.setTransform(-77,-30);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#006E47").s().p("AgtC2QgMgFAAgLQAAgIAMgFIAHgDQAHgDADgJQACgIAAgUIgBgRIAAgUIAAgbQAAgogBgLQgDgMgFgDIgLgEQgQgFAAgJQAAgFAFgFQAEgEALgFIAngMIAagFQAHAAADAFQADAFAAAMIAAAPIAAALIgCBAIAAACIgBA+QAAAYACAKQACAKAGADIAJAEQANAFAAAKQAAAKgMAEQgNAEghAAQgmAAgNgEgAgeiAQgMgIAAgOQAAgOANgKQAMgLARAAQAPAAALAKQALAJAAAOQAAAOgMAKQgMAJgQAAQgRAAgKgJg");
	this.shape_20.setTransform(-100.7,-30.1);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#006E47").s().p("AgqC3QgNgFAAgLQAAgIALgEIANgHQAEgFACgPIACgyIgBgoIAAgvIAAgUQAAhAgCgSQgCgTgGgDIgPgFQgQgFAAgJQAAgGAFgEQAFgFASgGIAigJIAZgEQAIAAADAFQADAFAAAMIAAATQgDBbAABbIACBXQABASAEAFIAPAHQALAFAAAKQAAAKgMAEQgNAEghAAQgmAAgMgEg");
	this.shape_21.setTransform(-115.8,-30.2);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#006E47").s().p("AhcBfQgkglAAg5QAAg5AmgmQAmglA4gBQA3AAAjAkQAjAjAAA4QAAA7glAnQgmAog3AAQg3AAgkgmgAgwhLQgPAVgBAiQABAxAVAiQAWAiAdAAQAZAAAPgVQAQgVAAgjQAAgwgWgiQgVgigdAAQgZAAgQAVg");
	this.shape_22.setTransform(-137.1,-24.3);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#006E47").s().p("AA5CzQgOgFgBgLQABgKAQgGIALgGQAEgCACgRIABg8IAAgjIgCgKQgDgEgMgDQgNgCgvAAIg2ACQgOABgEAEIgDAIIgBATIAAAUIABA8QACARAFACIALAGQAQAGAAAKQAAALgPAFQgNAFgpAAQgnAAgPgFQgOgFAAgLQAAgKAQgGIALgGQAFgEADggQACggAAhLIgChgQgCglgDgFQgDgDgOgGQgNgFAAgLQAAgKAMgEQALgDAtAAQAtAAALADQANAEAAAKQAAAKgQAHIgLAFQgFAEgCAPIgBBLQAAALAJADQAJAEAlAAIAVAAIA1gCQAQgCAFgDIADgFIAAgKIAAgMIgBg+QgCgNgEgDIgLgFQgQgHgBgKQABgKALgEQAMgDAtAAQAuAAALADQALAEAAAKQAAAKgQAHIgLAFQgFAEgDAjQgCAhAABFIACBiQACAmADAFQADADAOAGQANAGAAAJQAAALgOAFQgPAFgnAAQgoAAgOgFg");
	this.shape_23.setTransform(-171.1,-29.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.holidaytipsrecipes, new cjs.Rectangle(-192.3,-62.4,384.6,124.8), null);


(lib.holidayhostingtips = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E47").s().p("AgWCcIgggGIgJAGIgKACIgGgCIgGgEQgKgIgIgYQgJgZAAgWQAAgJAFgHQAFgGAIAAQAOAAAOAYIALASQAJAMAQAHQAPAHARAAQAUAAAMgKQALgKAAgRQAAgZgxgYIgSgJQgugXgRgTQgQgTAAgdQAAgnAbgYQAbgZAsAAIAUABIAVAEIAOgGIAKgCQAOAAAOAYQAOAYAAAaQAAAKgEAGQgFAGgJAAQgHAAgGgFQgHgGgJgPQgLgSgMgHQgMgIgRAAQgQAAgLAKQgLAKAAAPQAAAOALALQALAKAlATIADACQBUAoAAAxQAAApggAdQghAcgwAAg");
	this.shape.setTransform(161.2,42.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E47").s().p("AiRDNQgQgFAAgNQABgKANgFIAPgIQAGgGACgYQACgXABhLIAAgwQAAhSgDgXQgDgYgHgEIgNgFQgTgGAAgKQAAgHAFgGQAGgEAMgFIArgNQATgGALAAQAIAAAEAFQADAEAAALIAAAPIABAGIABACIANgJIALgIQATgOAQgHQARgGASAAQA3gBAkApQAjApAABBQAABIgoAuQgoAug9AAQgaAAgJgHQgKgIAAgLQAAgHAFgFQAEgFAJABIAIABIAKABQAiAAATgcQAUgcAAgtQABg0gWgfQgWgfghgBQggAAgSASQgRASgBAtIAAC+IACAeQACALAEAFQADAEAOAEIALAEIAHAFIACAJQAAALgSAFQgRAFgrgBQgrAAgPgEg");
	this.shape_1.setTransform(129.3,47.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E47").s().p("Ag1DWQgOgFAAgNQAAgKAOgFIAHgEQAJgEACgKQAEgKAAgXIAAgUIAAgYIAAgfQgBgwgCgNQgCgOgGgEIgOgFQgSgGgBgKQABgGAFgFQAGgGANgFIAtgOIAfgGQAIAAAEAGQADAFAAAOIAAASIAAANIgDBMIAAACIgBBKQAAAcADAMQACAMAHADIALAFQAQAGAAALQgBAMgPAFQgOAEgoAAQgsAAgPgFgAgliXQgNgKABgQQAAgRAOgMQAOgMAUAAQASAAAOALQANALgBAQQABARgOALQgPAMgTAAQgUAAgNgLg");
	this.shape_2.setTransform(103.4,35.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E47").s().p("Ag/DVQgQgFAAgNQAAgMAPgGQARgGACgFQAEgFACgxIACiOIgBhPIgDgwQgBgIgFgDQgFgCgMgBIgNAAQgVAAgMAGQgLAEgJAMIgJAUIgJAUIgIAKQgFAEgGAAQgJgBgEgHQgEgIAAgTQAAgnAJgYQAKgYAOgBIADAAQAYAEAkAAICwAAQAkAAAYgEIAEAAQAOABAJAYQAKAYAAAnQAAATgEAIQgFAHgJABIgKgEIgJgKIgJgUIgJgUQgIgMgMgEQgMgGgVAAIgMAAQgMABgFACQgFADgCAIIgCAwIgBBPIACCOQACAxADAFQADAFAQAGQAQAGAAAMQAAANgQAFQgSAGguAAQguAAgRgGg");
	this.shape_3.setTransform(75.2,35.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E47").s().p("AhvDEQgmgXAAghQAAgPAIgKQAIgKARAAQAMAAAIAHQAGAHAEAOQAHAWATANQATAMAkAAQAoAAAbgPQAagQAAgWQAAgPgKgHQgKgIgTAAIgjACIgtADQg1AAgdgSQgdgTAAgXQAAgQAKgOQALgOAWgNQgSgPgJgTQgJgUABgXQAAgxAkggQAlghA4AAIAgADIAuAJQALAAANgFQANgGATgNIAJAJIADAKQABANgKAMQgKAMgRAJIAJAYIADAZQAAAxgkAgQgkAeg7AAIgfgCIgdgHIgJAMIgEALQAAAOAPAHQAOAHAeAAIAtgDIAvgEQApAAAXARQAWARAAAgQAAAwgvAgQgvAfhHAAQg6AAgmgXgAgxiUQgQATAAAeQAAAeAPATQAQATAZAAQAYAAAQgTQARgTAAgeQAAgfgQgTQgQgTgZAAQgYAAgQAUg");
	this.shape_4.setTransform(23.6,47.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E47").s().p("AiTCVQgPgFAAgNQAAgKAPgGIAHgDQAIgEADgLQAEgKAAgWIgBgVIAAgYIAAgeQAAgvgCgPQgDgOgGgDIgOgFQgSgGAAgKQAAgHAGgFQAFgFANgGIAsgNIAfgGQAIAAAEAFQADAEAAAKIAAAUIABADIACABIACAAIABgBIAHgGIAGgGQAggfAlAAQAWAAAUAKQAUAJAOAQQAOARAGAWQAFAXAAAwIAAAoIAAAUIAAARQAAAVADAJQADAJAHAEIAIADQAPAGAAAKQAAANgOAEQgOAFguAAQgqAAgOgEQgPgFAAgLQAAgMAPgFIAMgFQAHgEACgNQADgNAAghQAAhegMgZQgMgYggAAQgPAAgOAKQgPAJgIARQgGANgDAXQgDAXAAA7QAAAdADAKQACAJAHAEIALAFQAPAFAAAMQAAALgPAFQgOAFgoAAQgtAAgPgFg");
	this.shape_5.setTransform(-11.7,42.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E47").s().p("Ag1DWQgPgFAAgNQAAgKAPgFIAHgEQAIgEAEgKQADgKAAgXIgBgUIAAgYIAAgfQAAgwgCgNQgDgOgFgEIgPgFQgRgGgBgKQABgGAFgFQAGgGANgFIAtgOIAfgGQAIAAAEAGQADAFAAAOIAAASIgBANIgCBMIAAACIgBBKQAAAcACAMQADAMAHADIALAFQAPAGAAALQAAAMgPAFQgOAEgoAAQgsAAgPgFgAgliXQgNgKAAgQQAAgRAPgMQAOgMAUAAQASAAANALQANALAAAQQAAARgNALQgOAMgVAAQgTAAgNgLg");
	this.shape_6.setTransform(-38.6,35.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006E47").s().p("AgQC0QgPgFgKgJQgLgKgEgRQgFgQAAgtIAAigIgbAAIgJgDIgCgHIAAgIQAAgJAfgbIAMgLIAMgKQAfgbALAAIAJACQADADAAAEIAAA5IBEAAQAHAAADACQADADAAAJIAAAHQAAAIgDADQgEAEgGAAIg+AAIgFACIgCAHIAACUQAAAnAHAKQAGAKASAAQAJAAAPgFIAVgFQAGAAAFAEQAEAEAAAGQAAAQgZAQQgaAPggAAQgSAAgPgFg");
	this.shape_7.setTransform(-57.8,39.7);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006E47").s().p("AgWCcIgggGIgJAGIgKACIgGgCIgGgEQgKgIgIgYQgJgZAAgWQAAgJAFgHQAFgGAIAAQAOAAAOAYIALASQAJAMAQAHQAPAHARAAQAUAAAMgKQALgKAAgRQAAgZgxgYIgSgJQgugXgRgTQgQgTAAgdQAAgnAbgYQAbgZAsAAIAUABIAVAEIAOgGIAKgCQAOAAAOAYQAOAYAAAaQAAAKgEAGQgFAGgJAAQgHAAgGgFQgHgGgJgPQgLgSgMgHQgMgIgRAAQgQAAgLAKQgLAKAAAPQAAAOALALQALAKAlATIADACQBUAoAAAxQAAApggAdQghAcgwAAg");
	this.shape_8.setTransform(-82.2,42.4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006E47").s().p("AhtBxQgqgtAAhDQAAhDAtgsQAsgtBDAAQBAgBAqArQApAqAABCQAABEgsAuQgtAwhAAAQhBAAgrgsgAg5hZQgSAYAAAoQAAA7AZApQAZAoAkAAQAdAAATgaQASgZAAgoQAAg5gagpQgZgngjAAQgeAAgSAYg");
	this.shape_9.setTransform(-112.2,42.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006E47").s().p("ABDDTQgRgFAAgNQAAgMATgHIANgHQAFgEACgTIAChGIAAgqIgDgMQgDgFgOgDQgPgCg4AAIhAACQgQABgFAEIgEAJIgBAXIAAAZIACBGQACATAFAEIANAHQATAHAAAMQAAANgRAFQgQAGgwAAQgvAAgQgGQgRgFAAgNQAAgMASgHIANgHQAHgFADgmQACgmAAhaIgChvQgDgtgEgFQgDgFgPgGQgQgHAAgMQAAgLANgFQANgFA2AAQA1AAAOAFQAOAFAAALQAAAMgTAIIgNAGQgGAEgCASIgCBZQAAAMAMAFQALADArAAIAZAAIA/gBQATgCAFgFIADgFIABgMIAAgNIgChKQgCgQgFgDIgNgGQgTgIAAgMQAAgLAOgFQAOgFA1AAQA2ABANAEQANAEAAAMQAAAMgTAIIgNAGQgGAEgDAqQgDAoAABPIADB1QACAtAEAGQADAFAQAGQAQAGAAAMQAAANgRAFQgRAGguAAQgwAAgQgGg");
	this.shape_10.setTransform(-152.2,36);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006E47").s().p("AiKDGQgOgMAAgTQAAgPAKgLQALgLAPABIANABIAJAIIAIAKQAIAMAGAAQAPABAQgWQAPgXAAgXQAAgagVgvIgDgHIgwhpIgbg6QgGgLgRgIQgLgEgDgEQgEgFAAgGQAAgNAQgGQAQgEAsAAQArAAAPAEQAPAFAAAMIgCAJIgFAGIgLAFQgMAEAAAGIAGAWIAYA9IAYA3QAIAPAEAAQADAAAHgOIAUgvIAWg8QAHgVAAgIQAAgJgRgJQgRgJAAgIQAAgLAOgEQAOgEAiAAQAkAAAMAEQANAFAAAMQAAALgRAEIgMAEQgRAKgUAzIgIAXIgnBgQgxB8gfAnQggAkgsABQgWAAgOgNg");
	this.shape_11.setTransform(23.3,-22.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#006E47").s().p("AA1CNIgQgQIgNAHQglAZgkAAQgsAAgbgaQgbgZAAgqQAAgwAigZQAjgbA/AAQAPAAAHAEQAIAEAAAMQAAARgVAAQgdAAgSAOQgSAPAAAZQAAAYAPAOQAQAPAbAAQAcAAANgNQAMgNAAggIAAhxQAAgagMgPQgLgOgUAAQgPAAgNAHQgMAGgMANIgHAIQgSAXgUAAQgMAAgHgHQgHgIAAgNQAAgcAjgTQAjgUA2AAQAhAAAYAJQAYAJANARQAJALAEASQADATAAArIAABgQAAARADAIQADAIAGACIAJADQATAFAAAKQAAAOgUAMQgUAMgbAAQgNAAgPgQg");
	this.shape_12.setTransform(-7.9,-28.7);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#006E47").s().p("AiDC2QgjgpAAhBQAAhJAogtQApguBAAAIAVACQAJADAFAHQAFAHAAAHQAAAQgTAAIgJgBIgIAAQghAAgUAbQgUAbAAAvQAAAzAWAfQAWAgAhgBQAfABASgSQARgRAAghIAAhSIAAiLQAAgVgEgHQgEgJgLgEIgIgCQgTgFAAgLQAAgIAIgGQAHgFAXgJIAhgKIAcgDQAKAAAFAGQAEAGAAANIAAAPIgDC5IACB9QACAdAEAEIAVAHQAQAEAAAKQAAAOgrAOIgeAIIgXACQgJAAgDgEQgEgFAAgKIAAgPIgBgFIgBgCIgKAGIgNAKQgSAOgQAGQgRAGgTAAQg4AAgjgog");
	this.shape_13.setTransform(-41.5,-35.4);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#006E47").s().p("Ag1DWQgOgFAAgNQAAgKAOgFIAHgEQAJgEACgKQAEgKAAgXIAAgUIAAgYIAAgfQgBgwgCgNQgCgOgGgEIgPgFQgRgGgBgKQABgGAFgFQAGgGANgFIAtgOIAfgGQAIAAAEAGQADAFAAAOIAAASIAAANIgDBMIAAACIgBBKQAAAcADAMQACAMAHADIALAFQAQAGAAALQgBAMgPAFQgOAEgoAAQgsAAgPgFgAgliXQgNgKABgQQAAgRAOgMQAOgMAUAAQASAAAOALQANALgBAQQABARgOALQgPAMgTAAQgUAAgNgLg");
	this.shape_14.setTransform(-69.4,-35.5);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#006E47").s().p("AgyDXQgPgFAAgNQAAgJANgFIAPgIQAFgGACgSIACg7IAAgvIAAg4IAAgXQAAhMgDgVQgCgWgHgDIgSgHQgTgGAAgKQAAgIAGgFQAGgEAVgIIAogLIAegEQAJgBAEAHQAEAFAAAOIgBAXQgDBrAABsIACBmQACAWAFAGIARAJQANAFAAAMQAAALgPAFQgPAEgnABQgtAAgOgGg");
	this.shape_15.setTransform(-87.1,-35.6);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#006E47").s().p("AhtBwQgqgsAAhDQAAhCAtguQAsgsBDgBQBAABAqAqQApApAABDQAABEgsAvQgtAuhAAAQhBAAgrgsgAg5hZQgSAYAAApQAAA6AZApQAZAnAkAAQAdAAATgYQASgZAAgpQAAg6gagoQgZgogjABQgegBgSAZg");
	this.shape_16.setTransform(-112.2,-28.7);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#006E47").s().p("ABDDTQgRgFAAgNQAAgMATgIIANgGQAFgEACgTIAChGIAAgqIgDgMQgDgGgOgCQgPgCg4AAIhAABQgQACgFAFIgEAJIgBAWIAAAZIACBGQACATAFAEIANAGQATAIAAAMQAAANgRAFQgQAFgwABQgvgBgQgFQgRgFAAgNQAAgMASgIIANgGQAHgFADgmQACgmAAhaIgChvQgDgtgEgGQgDgEgPgGQgQgHAAgMQAAgMANgEQANgFA2ABQA1gBAOAFQAOAEAAAMQAAAMgTAHIgNAHQgGAEgCASIgCBZQAAAMAMAEQALAEArABIAZAAIA/gCQATgCAFgEIADgGIABgMIAAgOIgChJQgCgQgFgDIgNgHQgTgHAAgMQAAgMAOgEQAOgFA1ABQA2AAANADQANAFAAAMQAAAMgTAHIgNAHQgGAFgDAoQgDAoAABQIADB0QACAuAEAGQADAFAQAFQAQAHAAAMQAAANgRAFQgRAFguABQgwgBgQgFg");
	this.shape_17.setTransform(-152.2,-35.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.holidayhostingtips, new cjs.Rectangle(-176.8,-73.2,353.8,146.5), null);


(lib.greyrectangle = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#999999").ss(1,1,1).p("EhKEgThMCUJAAAMAAAAnDMiUJAAAg");
	this.shape.setTransform(0,0,1.022,0.996);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.greyrectangle, new cjs.Rectangle(-485.5,-125.5,971,251), null);


(lib.getpartystarted = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E47").s().p("Ag/BLQgDAAgCgBQgDgCAAgDIAAiIQAAgDACgCQACgCAEAAIA4AAIAPABIAPAEQAPAFALAKQALAKAGAOQADAHACAIQABAHAAAIQAAARgGAOQgDAHgFAGIgKALIgMAJIgNAGQgPAFgPAAgAgpgtQgCACAAAEIAABSQAAACADACQADACACAAIAcAAQAJAAAKgDQAKgEAHgGQAHgHAEgJQAEgJAAgLQAAgKgEgJQgEgJgHgGQgHgHgKgDQgKgEgJAAIgbAAQgEAAgDADg");
	this.shape.setTransform(136.1,-0.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E47").s().p("AgzBLIgEgBQgDgCAAgCIAAiLQAAAAAAgBQAAAAAAgBQABAAAAgBQABAAAAgBIAFgBIBpAAQAAAAABAAQAAAAABABQAAAAABAAQAAABAAAAIACAFIAAAFIAAAFIgBAFQgBADgDABIhOAAQgBAAAAAAQgBABAAAAQgBAAAAABQgBAAAAABQgBAAAAABQAAAAgBABQAAAAAAABQAAAAAAABIAAAUQAAAEACABQACACADAAIAyAAQAAAAABAAQAAAAABABQAAAAABAAQAAABAAAAIACAGIAAAGIAAADQAAAHgGABIgwAAQgDAAgDADQgCACAAADIAAAXQAAADACACQACACADAAIBNAAQAEADAAAGIABAEIgBAGIgBAFQgBABAAAAQAAAAgBABQAAAAgBAAQgBAAAAAAg");
	this.shape_1.setTransform(119.8,-0.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E47").s().p("AgCBMIgHgBQgEgCAAgFIAAhuQAAgEgCgCQgBgBgGAAIgMAAIgLAAIgGAAQgFAAgBgDIgCgHIAAgGIABgEIACgFQABAAAAAAQABAAAAgBQABAAAAAAQABAAABAAIBoAAQAEAAABADQACADAAAEIAAAFIgBAEIgCAFQgBAAAAABQgBAAAAAAQgBABAAAAQgBAAgBAAIgeAAQgDAAgDABQgCACAAAFIAABtQAAAEgCACIgEACIgFAAg");
	this.shape_2.setTransform(105.1,-0.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E47").s().p("AAmBMIgEgBIgCgBIgCgCIgagoIgEgFQgDgCgEAAIgTAAQgDAAgCADQgDACAAADIABAlQAAABgBAAQAAABAAABQAAAAgBAAQAAABgBAAIgFACIgHAAIgEAAQgEAAgDgCQgCgBAAgFIAAiKQAAgBAAAAQAAgBAAAAQABgBAAAAQAAgBABAAQAAgBABAAQAAAAABAAQAAgBABAAQABAAAAAAIBAAAQALAAALAEQAJADAIAHQAGAGAEAKQAEAJAAAMQABANgFAIQgFAHgFAFIgLAIQgFADAAADIAAAEIAGAIIAJAMIAIAMQADAGAAACQAAABAAAAQAAABgBABQAAAAAAABQgBAAAAABIgFADIgFACIgFABgAgfgwQgDACAAAEIAAAiQAAAEADACQADACAEAAIAeAAQAHAAAEgBQAGgCADgDQAFgDACgEQACgFAAgHQAAgMgJgGQgDgEgGgBQgEgCgHAAIgeAAQgEAAgDACg");
	this.shape_3.setTransform(91.4,-0.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E47").s().p("AA8BMIgFAAIgIgBQgEgBgCgEIgIgUIgDgDIgEgCIgyAAIgCABIgCABIgDACIgBABIgIAUIgDADIgEACIgFABIgEAAIgEAAIgEgBIgEgBQgBgBAAAAQAAAAgBAAQAAgBAAAAQAAgBAAAAIA+iOQAAgBAAAAQABgBAAAAQABgBAAAAQABAAABAAIAEgBIAGAAQAFABABADIA7CNIAAABQAAABAAAAQAAABAAAAQAAABgBAAQAAAAAAABIgFABgAgBgXIgBACIgCAEIgDAHIgEAJIgDAHIgDAHIgBADIABAEIADABIAeAAIADgBIABgDIgCgHIgFgLIgGgNIgDgIQAAAAgBAAQAAgBgBAAQAAAAgBAAQAAAAgBAAg");
	this.shape_4.setTransform(75.2,-0.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E47").s().p("AgCBMIgHgBQgEgCAAgFIAAhuQAAgEgCgCQgBgBgGAAIgMAAIgLAAIgGAAQgFAAgBgDIgCgHIAAgGIABgEIACgFQABAAAAAAQABAAAAgBQABAAAAAAQABAAABAAIBoAAQAEAAABADQACADAAAEIAAAFIgBAEIgCAFQgBAAAAABQgBAAAAAAQgBABAAAAQgBAAgBAAIgeAAQgDAAgDABQgCACAAAFIAABtQAAAEgCACIgEACIgFAAg");
	this.shape_5.setTransform(61.3,-0.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E47").s().p("AghBIQgQgFgMgMIgCgDIgBgDQAAgBAAAAQAAgBABAAQAAgBAAAAQABgBAAgBIAFgEIAFgFIAFgBQAEAAADACIAKAHIANAHQAHACAKAAIALgBQAGgBAGgCQAFgDAEgEQAEgFAAgGQAAgHgFgDQgEgEgHgCIgPgCIgRgDIgSgEQgJgDgGgDQgHgFgFgHQgEgHAAgMQAAgMAGgJQAGgIAJgGQAKgFALgDQALgCAJAAIAOABIAPADQAIACAHAEQAHAEAFAFIABACIAAACQAAAEgCACIgEAFIgGADIgGABIgEAAQgIgHgJgEQgJgEgKAAIgKABQgGABgEADQgFABgDAEQgDAFAAAGQAAAIAHAEQAHADALACIAWADQANABALAEQAKAFAIAHQAHAJAAAPQAAANgGAKQgHAJgJAHQgKAGgMADQgLACgLAAQgQABgQgHg");
	this.shape_6.setTransform(47.3,-0.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006E47").s().p("AgFBPIgEgBIgDgCIgBgDIAAg2QAAgDgCgFIgDgIIgshCIAAgCQAAgBAAAAQAAgBABgBQAAAAAAgBQABAAAAgBIAFgEIAFgCIAGgBIAEABIAEADIAeAxIADADIADABIADgCIADgCIAegxQACgDACgBIAGgBIAEABIAGACIAFAEQAAAAABABQAAAAAAABQABAAAAABQAAABAAAAIAAACIgBACIgrBCIgEAJIgBAEIgBADIAAA1QgCAGgFAAIgIABg");
	this.shape_7.setTransform(25.9,-0.7);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006E47").s().p("AgCBMIgHgBQgEgCAAgFIAAhuQAAgEgCgCQgBgBgGAAIgMAAIgLAAIgGAAQgFAAgBgDIgCgHIAAgGIABgEIACgFQABAAAAAAQABAAAAgBQABAAAAAAQABAAABAAIBoAAQAEAAABADQACADAAAEIAAAFIgBAEIgCAFQgBAAAAABQgBAAAAAAQgBABAAAAQgBAAgBAAIgeAAQgDAAgDABQgCACAAAFIAABtQAAAEgCACIgEACIgFAAg");
	this.shape_8.setTransform(12.4,-0.4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006E47").s().p("AAmBMIgEgBIgDgBIgBgCIgagoIgEgFQgDgCgEAAIgTAAQgDAAgCADQgDACAAADIABAlQAAABgBAAQAAABAAABQAAAAgBAAQAAABgBAAIgFACIgHAAIgEAAQgEAAgDgCQgCgBAAgFIAAiKQAAgBAAAAQAAgBAAAAQABgBAAAAQAAgBABAAQAAgBABAAQAAAAABAAQAAgBABAAQABAAAAAAIBAAAQALAAALAEQAJADAIAHQAGAGAFAKQADAJAAAMQABANgFAIQgFAHgFAFIgLAIQgFADAAADIAAAEIAGAIIAJAMIAIAMQADAGAAACQAAABAAAAQAAABgBABQAAAAAAABQgBAAAAABIgFADIgFACIgFABgAgfgwQgDACAAAEIAAAiQAAAEADACQADACAEAAIAeAAQAHAAAEgBQAGgCADgDQAFgDACgEQACgFAAgHQAAgMgJgGQgDgEgGgBQgEgCgHAAIgeAAQgEAAgDACg");
	this.shape_9.setTransform(-1.3,-0.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006E47").s().p("AA8BMIgFAAIgIgBQgEgBgCgEIgIgUIgDgDIgEgCIgyAAIgCABIgCABIgDACIgBABIgIAUIgDADIgEACIgFABIgEAAIgEAAIgEgBIgEgBQgBgBAAAAQAAAAgBAAQAAgBAAAAQAAgBAAAAIA+iOQAAgBAAAAQABgBAAAAQABgBAAAAQABAAABAAIAEgBIAGAAQAFABABADIA7CNIAAABQAAABAAAAQAAABAAAAQAAABgBAAQAAAAAAABIgFABgAgBgXIgBACIgCAEIgDAHIgEAJIgDAHIgDAHIgBADIABAEIADABIAeAAIADgBIABgDIgCgHIgFgLIgGgNIgDgIQAAAAgBAAQAAgBgBAAQAAAAgBAAQAAAAgBAAg");
	this.shape_10.setTransform(-17.5,-0.5);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006E47").s().p("Ag1BNQgGAAgDgGIAAiOQAAgBAAAAQABgBAAAAQAAgBABAAQAAAAABgBIAEgBIBBAAQAKAAAKADQAJAEAIAGQAHAGAFAJQAEAJAAALIgBAHIgCAHQgFAOgKAGQgKAHgNACQgMADgMgBIgaAAIgCABIgCABQgCADAAADIAAAuIgDAEIgFABIgGABgAgggvQgCADAAADIAAAaQAAAAAAABQAAABAAAAQABABAAAAQAAABABAAQACACADAAIAlAAIAJgBQAEgBAEgDQADgDACgEQACgEAAgFQAAgEgCgEQgCgDgDgDIgHgEIgIgBIgmAAQgEAAgCACg");
	this.shape_11.setTransform(-31.9,-0.5);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#006E47").s().p("AgzBLIgEgBQgDgCAAgCIAAiLQAAAAAAgBQAAAAAAgBQABAAAAgBQABAAAAgBIAFgBIBpAAQAAAAABAAQAAAAABABQAAAAABAAQAAABAAAAIACAFIAAAFIAAAFIgBAFQgBADgDABIhOAAQgBAAAAAAQAAABgBAAQAAAAgBABQgBAAAAABQgBAAAAABQAAAAgBABQAAAAAAABQAAAAAAABIAAAUQAAAEACABQACACADAAIAyAAQAAAAABAAQAAAAABABQAAAAABAAQAAABAAAAIACAGIAAAGIAAADQAAAHgGABIgwAAQgDAAgDADQgCACAAADIAAAXQAAADACACQACACADAAIBNAAQAEADAAAGIABAEIgBAGIgBAFQgBABAAAAQAAAAgBABQAAAAgBAAQAAAAgBAAg");
	this.shape_12.setTransform(-54.1,-0.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#006E47").s().p("Ag1BNIgFgBQgCgBgBgDIAAiQIADgDIAFgBIAGgBIAFAAQAGAAADAGIAAAwQAAADACADQACACADAAIA0AAQADAAADgCQACgCAAgEIAAgwQADgFAFAAIAJAAIAGABQADABACADIAACPQgCAFgFAAIgJAAIgGgBQgDgBgDgCIAAg2QAAgDgCgDQgCgCgEAAIgyAAQgEAAgCADQgDADAAADIAAA0QAAADgDABIgFABIgGABg");
	this.shape_13.setTransform(-70.6,-0.5);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#006E47").s().p("AgCBMIgHgBQgEgCAAgFIAAhuQAAgEgCgCQgBgBgGAAIgMAAIgLAAIgGAAQgFAAgBgDIgCgHIAAgGIABgEIACgFQABAAAAAAQABAAAAgBQABAAAAAAQABAAABAAIBoAAQAEAAABADQACADAAAEIAAAFIgBAEIgCAFQgBAAAAABQgBAAAAAAQgBABAAAAQgBAAgBAAIgeAAQgDAAgDABQgCACAAAFIAABtQAAAEgCACIgEACIgFAAg");
	this.shape_14.setTransform(-85.6,-0.4);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#006E47").s().p("AgCBMIgHgBQgEgCAAgFIAAhuQAAgEgCgCQgBgBgGAAIgMAAIgLAAIgGAAQgFAAgBgDIgCgHIAAgGIABgEIACgFQABAAAAAAQABAAAAgBQABAAAAAAQABAAABAAIBoAAQAEAAABADQACADAAAEIAAAFIgBAEIgCAFQgBAAAAABQgBAAAAAAQgBABAAAAQgBAAgBAAIgeAAQgDAAgDABQgCACAAAFIAABtQAAAEgCACIgEACIgFAAg");
	this.shape_15.setTransform(-105.2,-0.4);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#006E47").s().p("AgzBLIgEgBQgDgCAAgCIAAiLQAAAAAAgBQAAAAAAgBQABAAAAgBQABAAAAgBIAFgBIBpAAQAAAAABAAQAAAAABABQAAAAABAAQAAABAAAAIACAFIAAAFIAAAFIgBAFQgBADgDABIhOAAQgBAAAAAAQAAABgBAAQAAAAgBABQgBAAAAABQgBAAAAABQAAAAgBABQAAAAAAABQAAAAAAABIAAAUQAAAEACABQACACADAAIAyAAQAAAAABAAQAAAAABABQAAAAABAAQAAABAAAAIACAGIAAAGIAAADQAAAHgGABIgwAAQgDAAgDADQgCACAAADIAAAXQAAADACACQACACADAAIBNAAQAEADAAAGIABAEIgBAGIgBAFQgBABAAAAQAAAAgBABQAAAAgBAAQAAAAgBAAg");
	this.shape_16.setTransform(-118.4,-0.6);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#006E47").s().p("AgMBNIgPgEIgOgHIgMgKIgJgLIgIgOQgHgOAAgRQAAgIACgHIAFgPQAGgPALgKIAMgJQAHgFAHgDIAPgEQAIgCAIAAQAJAAAIACQAJACAIAEQAPAHAMANIABADQAAACgCADIgFAFIgGAFIgFABQgDAAgDgDIgJgHQgEgEgIgDQgHgDgKAAQgKAAgJAEQgKAEgHAHQgHAHgEAKQgEAJAAAKQAAAKAEAKQAEAJAHAIQAHAHAKAEQAJAEAKAAIAKgBIALgCQAFgCAEgDQAEgDADgFIAAgDQAAAAAAgBQAAgBAAAAQAAgBgBAAQAAgBgBAAIgFgCIgbAAQAAAAgBAAQAAAAgBAAQAAAAgBgBQAAAAAAgBIgCgEIgBgGIAAgFIABgFQACgDADgBIA/AAIACABIADACQADAHAAAHIgBAHIgBAGQgFALgHAJQgHAJgKAGQgJAGgLADQgLAEgMAAQgIAAgIgCg");
	this.shape_17.setTransform(-136.1,-0.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.getpartystarted, new cjs.Rectangle(-146.6,-13,293.4,26.1), null);


(lib.getinspired = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgTBCQgIgEgGgGQgFgGgDgIQgDgJAAgJQAAgJADgJQADgHAFgGQAGgGAIgDQAIgEAJAAQAKAAAIAFQAHAEAFAGIAAAAIAAg/IARAAIAACHIgQAAIAAgOIgBAAQgEAIgJAEQgIAEgIAAQgKAAgIgDgAgLgDQgFACgEAEQgDAEgCAFQgCAGAAAGQAAAGACAFQACAGADAEQAEAFAFACQAFADAHAAQAGAAAFgDQAGgCADgEQAEgFACgFQACgGAAgGQAAgGgCgGQgCgFgEgEQgDgEgGgCQgFgDgGAAQgHAAgFADg");
	this.shape.setTransform(45.2,-0.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgPAqQgIgEgFgFQgHgHgDgIQgEgIAAgKQAAgJAEgIQADgIAGgHQAGgGAIgDQAJgDAHAAQAKAAAHADQAIADAGAFQAFAGACAJQAEAIAAAKIAAACIAAADIhDAAQAAAFACAFQACAFAEAEQAEADAFACQAFACAEAAQAJAAAHgEQAFgEAEgFIAMAJQgHAJgJAFQgEACgFABIgMABQgIAAgJgDgAAagHQgBgFgBgEQgCgFgDgDQgDgDgEgCQgEgCgHAAQgEAAgFACQgEACgEADQgEADgBAFQgDAEAAAFIAyAAIAAAAg");
	this.shape_1.setTransform(34.3,2.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgXAsIAAhCIAAgJIgBgKIAQAAIABAIIAAAHIAAAAQADgIAHgEQADgDAEgBIAIgBIAHABIgBAPIgIAAQgFAAgFACQgEACgDAEQgDAEgBAFIgBAKIAAAsg");
	this.shape_2.setTransform(26.1,2.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgHBAIAAhVIAPAAIAABVgAgHgsQgDgDAAgEQAAgFADgEQADgCAEAAQAFAAADACQADAEAAAFQAAAEgDADQgDADgFAAQgEAAgDgDg");
	this.shape_3.setTransform(19.5,0.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgsBBIAAh/IAQAAIAAANIABAAQAEgHAIgEQAIgEAKAAQAJAAAIADQAIADAGAHQAFAGADAIQADAIAAAJQAAAKgDAIQgDAHgFAGQgGAHgIADQgIAEgKAAQgIAAgIgEQgIgEgFgHIAAAAIAAA3gAgLgwQgGADgDAEQgEAEgCAGQgCAFAAAHQAAAGACAFQACAGAEADQADAEAGADQAFACAGAAQAHAAAFgCQAFgDAEgEQADgEACgFQACgGAAgGQAAgGgCgFQgCgGgDgEQgEgEgFgDQgFgCgHAAQgGAAgFACg");
	this.shape_4.setTransform(11.3,4.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgSApQgJgDgGgJIAMgKQADAGAGACQAHAEAGAAIAGgBIAFgCIAEgDQACgCAAgEQAAgGgGgDQgGgDgKgCIgIgDQgFgBgDgCQgEgDgCgEQgDgEAAgGQAAgHADgFQADgFAEgDQAFgDAGgCIALgBQAJAAAIADQAJAEAFAHIgMAKQgDgFgFgDQgFgDgHAAIgFABIgFACQAAAAgBABQAAAAgBAAQAAABgBAAQAAABAAAAQgCACAAAEQAAAFAFADQAFACAJACIALAEIAJADIAGAIQACAEAAAFQAAAIgDAFQgCAFgFADQgFAEgGACQgGABgHAAQgIAAgKgEg");
	this.shape_5.setTransform(0.9,2.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAWAsIAAgvIgBgJIgDgJQgCgDgEgDQgEgCgGAAQgJAAgGAIQgHAIAAAMIAAAtIgRAAIAAhCIAAgJIAAgKIAQAAIAAAIIAAAGIABAAIAEgGIAHgFIAIgEIAIgBQAIAAAGADQAGADAEAEQAEAFACAGQABAHAAAHIAAA0g");
	this.shape_6.setTransform(-8.6,2.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgHBAIAAhVIAPAAIAABVgAgHgsQgDgDAAgEQAAgFADgEQADgCAEAAQAFAAADACQADAEAAAFQAAAEgDADQgDADgFAAQgEAAgDgDg");
	this.shape_7.setTransform(-16.6,0.2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgEAxQgHgHAAgNIAAgtIgQAAIAAgOIAQAAIAAgZIAQAAIAAAZIAXAAIAAAOIgXAAIAAArQAAAIADADQADAEAGAAIAFgBIAFgCIABAOIgHACIgIABQgMAAgFgHg");
	this.shape_8.setTransform(-27.2,1.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgOAqQgJgEgGgFQgFgHgEgIQgEgIABgKQgBgJAEgIQADgIAGgHQAGgGAIgDQAJgDAIAAQAJAAAHADQAJADAFAFQAFAGADAJQACAIAAAKIAAACIAAADIhCAAQAAAFACAFQADAFADAEQAEADAFACQAFACAFAAQAIAAAGgEQAHgEADgFIAMAJQgGAJgKAFQgFACgEABIgLABQgJAAgIgDgAAZgHQABgFgCgEQgCgFgCgDQgDgDgFgCQgEgCgGAAQgFAAgFACQgFACgDADQgDADgCAFQgDAEAAAFIAxAAIAAAAg");
	this.shape_9.setTransform(-35.6,2.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgQA+QgNgFgJgJQgJgJgFgMQgFgMAAgPQAAgOAFgMQAFgNAJgJIAKgIIAMgFQAMgFAOAAIAOABQAHABAGADQAMAEAIAHIgMAOQgGgHgJgEIgJgDIgLgBQgKAAgJAEQgJAFgGAHQgHAGgDAKQgEAJAAAKQAAAKAEAKQADAJAHAHQAGAHAJAEQAJAEALAAQAIAAAIgCQAIgBAFgDIAAgkIgcAAIAAgOIAuAAIAAA9QgKAFgMADQgQADgKAAQgOAAgMgFg");
	this.shape_10.setTransform(-48.5,0.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.getinspired, new cjs.Rectangle(-57.2,-13,111,26.1), null);


(lib.fourteentopright_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.fourteentopright();
	this.instance.parent = this;
	this.instance.setTransform(-155,-95);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.fourteentopright_1, new cjs.Rectangle(-155,-95,310,190), null);


(lib.fourteentable_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.fourteentable();
	this.instance.parent = this;
	this.instance.setTransform(-485,-125);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.fourteentable_1, new cjs.Rectangle(-485,-125,970,250), null);


(lib.fourteenrectangle = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D63900").s().p("AqJDXQhZAAg/g/Qg/g/AAhZQAAhYA/g/QA/g/BZAAIUTAAQBZAAA/A/QA/A/AABYQAABZg/A/Qg/A/hZAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.fourteenrectangle, new cjs.Rectangle(-86.5,-21.5,173.1,43), null);


(lib.fourteenbottomright_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.fourteenbottomright();
	this.instance.parent = this;
	this.instance.setTransform(-147.5,-93.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.fourteenbottomright_1, new cjs.Rectangle(-147.5,-93.5,295,187), null);


(lib.fourteenbottomleft_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.fourteenbottomleft();
	this.instance.parent = this;
	this.instance.setTransform(-67.5,-26);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.fourteenbottomleft_1, new cjs.Rectangle(-67.5,-26,135,52), null);


(lib.ctavideorollover = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#B63100").s().p("AqJDXQhZAAg/g/Qg/g/AAhZQAAhYA/g/QA/g/BZAAIUTAAQBZAAA/A/QA/A/AABYQAABZg/A/Qg/A/hZAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.ctavideorollover, new cjs.Rectangle(-86.5,-21.5,173.1,43), null);


(lib.blackwideskyscraper = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("EgRBA2FMAAAhsJMAiDAAAMAAABsJg");
	this.shape.setTransform(0,0,0.753,0.867);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.blackwideskyscraper, new cjs.Rectangle(-82.1,-300,164.3,600.1), null);


(lib.fourteenrollover = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_1 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(1).call(this.frame_1).wait(29));

	// cta-rollover
	this.instance = new lib.ctavideorollover();
	this.instance.parent = this;
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({alpha:1},9).wait(2).to({alpha:0},10).wait(8));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-86.5,-21.5,173.1,43);


// stage content:
(lib.billboardfourteenupdatedcta = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_49 = function() {
		//onhover event to reveal green cta rectangle over orange rectangle
		this.btn_main.addEventListener("mouseover", fl_MouseOverHandler.bind(this));
		this.btn_main.addEventListener("mouseout", fl_MouseOutHandler.bind(this));
		
		function fl_MouseOverHandler()
		{
			this.cta_rollover.gotoAndPlay(2);
		}
		
		function fl_MouseOutHandler()
		{
		this.cta_rollover.gotoAndPlay(13);
		}
	}
	this.frame_228 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(49).call(this.frame_49).wait(179).call(this.frame_228).wait(4));

	// button
	this.btn_main = new lib.mainbutton();
	this.btn_main.parent = this;
	this.btn_main.setTransform(486.2,125.3,4.708,0.381,0,0,0,0.3,0.8);
	new cjs.ButtonHelper(this.btn_main, 0, 1, 2, false, new lib.mainbutton(), 3);

	this.timeline.addTween(cjs.Tween.get(this.btn_main).wait(232));

	// grey-rectangle
	this.instance = new lib.greyrectangle();
	this.instance.parent = this;
	this.instance.setTransform(485,125);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(232));

	// fade-from-white
	this.instance_1 = new lib.blackwideskyscraper();
	this.instance_1.parent = this;
	this.instance_1.setTransform(486.8,125.1,5.906,0.417,0,0,0,0.4,0.2);
	this.instance_1.filters = [new cjs.ColorFilter(1, 1, 1, 1, 255, 255, 255, 0)];
	this.instance_1.cache(-84,-302,168,604);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({regX:0.1,regY:0.4,x:488.7,alpha:0},9).wait(223));

	// kale-logo
	this.instance_2 = new lib.kalelogo();
	this.instance_2.parent = this;
	this.instance_2.setTransform(851.8,56.7);
	this.instance_2.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(9).to({scaleX:0.05,scaleY:0.05},0).to({scaleX:1.14,scaleY:1.14,alpha:1},6,cjs.Ease.get(1)).to({scaleX:1,scaleY:1},7,cjs.Ease.get(1)).wait(210));

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("Egv/AhIMAAAhCQMBrGAAAMAAABCQg");
	mask.setTransform(378.3,132.1);

	// get-inspired
	this.instance_3 = new lib.getinspired();
	this.instance_3.parent = this;
	this.instance_3.setTransform(135.3,206.5);
	this.instance_3.alpha = 0;

	var maskedShapeInstanceList = [this.instance_3];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(49).to({x:-104.7},0).to({x:155.3,alpha:1},10,cjs.Ease.get(1)).to({x:135.3},8,cjs.Ease.get(1)).wait(165));

	// mask (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	mask_1.graphics.p("Eg1DAhIMAAAhCQMBx2AAAMAAABCQg");
	mask_1.setTransform(389.1,132.1);

	// cta-rollover
	this.cta_rollover = new lib.fourteenrollover();
	this.cta_rollover.parent = this;
	this.cta_rollover.setTransform(136,207.6);
	this.cta_rollover.alpha = 0;

	var maskedShapeInstanceList = [this.cta_rollover];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.cta_rollover).wait(49).to({x:-104},0).to({x:156,alpha:1},10,cjs.Ease.get(1)).to({x:136},8,cjs.Ease.get(1)).wait(165));

	// mask (mask)
	var mask_2 = new cjs.Shape();
	mask_2._off = true;
	mask_2.graphics.p("Eg1DAhIMAAAhCQMBx2AAAMAAABCQg");
	mask_2.setTransform(389.1,132.1);

	// cta-rectangle
	this.cta_rollover_1 = new lib.fourteenrectangle();
	this.cta_rollover_1.parent = this;
	this.cta_rollover_1.setTransform(136,207.6);
	this.cta_rollover_1.alpha = 0;

	var maskedShapeInstanceList = [this.cta_rollover_1];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_2;
	}

	this.timeline.addTween(cjs.Tween.get(this.cta_rollover_1).wait(49).to({x:-104},0).to({x:156,alpha:1},10,cjs.Ease.get(1)).to({x:136},8,cjs.Ease.get(1)).wait(165));

	// mask (mask)
	var mask_3 = new cjs.Shape();
	mask_3._off = true;
	mask_3.graphics.p("Eg1DAhIMAAAhCQMBx2AAAMAAABCQg");
	mask_3.setTransform(389.1,132.1);

	// get-the-party-started
	this.instance_4 = new lib.getpartystarted();
	this.instance_4.parent = this;
	this.instance_4.setTransform(196.2,38.5);
	this.instance_4.alpha = 0;

	var maskedShapeInstanceList = [this.instance_4];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_3;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(207).to({x:-243.8},0).to({x:216.2,alpha:1},10,cjs.Ease.get(1)).to({x:196.2},8,cjs.Ease.get(1)).wait(7));

	// mask (mask)
	var mask_4 = new cjs.Shape();
	mask_4._off = true;
	mask_4.graphics.p("Eg1DAhIMAAAhCQMBx2AAAMAAABCQg");
	mask_4.setTransform(389.1,132.1);

	// holiday-tips, recipes
	this.instance_5 = new lib.holidaytipsrecipes();
	this.instance_5.parent = this;
	this.instance_5.setTransform(241.8,113.4);
	this.instance_5.alpha = 0;

	var maskedShapeInstanceList = [this.instance_5];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_4;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(207).to({x:-198.2},0).to({x:261.8,alpha:1},10,cjs.Ease.get(1)).to({x:241.8},8,cjs.Ease.get(1)).wait(7));

	// sweet inspiration
	this.instance_6 = new lib.sweetinspiration();
	this.instance_6.parent = this;
	this.instance_6.setTransform(201.9,91.7);
	this.instance_6.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(147).to({alpha:1},10).wait(40).to({alpha:0},5).wait(30));

	// holiday-hosting
	this.instance_7 = new lib.holidayhostingtips();
	this.instance_7.parent = this;
	this.instance_7.setTransform(226.4,91.7);
	this.instance_7.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(97).to({alpha:1},10).wait(40).to({alpha:0},5).wait(80));

	// mask (mask)
	var mask_5 = new cjs.Shape();
	mask_5._off = true;
	mask_5.graphics.p("Eg1DAhIMAAAhCQMBx2AAAMAAABCQg");
	mask_5.setTransform(389.1,132.1);

	// party-ready-recipes
	this.instance_8 = new lib.partyreadyrecipes();
	this.instance_8.parent = this;
	this.instance_8.setTransform(221.3,91.7);
	this.instance_8.alpha = 0;

	var maskedShapeInstanceList = [this.instance_8];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_5;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(39).to({x:-188.7},0).to({x:241.3,alpha:1},10,cjs.Ease.get(1)).to({x:221.3},8,cjs.Ease.get(1)).wait(40).to({alpha:0},5).wait(130));

	// bottom-right
	this.instance_9 = new lib.fourteenbottomright_1();
	this.instance_9.parent = this;
	this.instance_9.setTransform(822.5,156.5);
	this.instance_9.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(24).to({alpha:1},10).wait(198));

	// top-right
	this.instance_10 = new lib.fourteentopright_1();
	this.instance_10.parent = this;
	this.instance_10.setTransform(568.2,95);
	this.instance_10.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(19).to({alpha:1},10).wait(203));

	// bottom-left
	this.instance_11 = new lib.fourteenbottomleft_1();
	this.instance_11.parent = this;
	this.instance_11.setTransform(296.2,224);
	this.instance_11.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(14).to({alpha:1},10).wait(208));

	// top-left
	this.instance_12 = new lib.topleftfourteen();
	this.instance_12.parent = this;
	this.instance_12.setTransform(31,28);
	this.instance_12.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(9).to({alpha:1},10).wait(213));

	// table
	this.instance_13 = new lib.fourteentable_1();
	this.instance_13.parent = this;
	this.instance_13.setTransform(485,125);

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(232));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(484.6,109.2,970.4,265.9);
// library properties:
lib.properties = {
	id: '85088BD5353243C8B4895C262600CED3',
	width: 970,
	height: 250,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	webfonts: {},
	manifest: [
		{src:"images/fourteenbottomright.png", id:"fourteenbottomright"},
		{src:"images/index_atlas_NP_.jpg", id:"index_atlas_NP_"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['85088BD5353243C8B4895C262600CED3'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;